### ISSUE TITLE
Questions regarding Section 5.3

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#105]
5.3. Rules for Handling MasterArbitrationUpdate Messages Received from Controllers

Regarding 1. (b) "If the election_id is already used by another
controller for the same (device_id, role_id)", how does the server
distinguish whether the message is from "another controller" or from
one of the controllers it already has active sessions with?  Is some
kind of id (e.g. an IP address?) communicated to the server when a new
gRPC session is initiated?

2. (b) "If the device_id does not match the one already assigned to
this stream".  Is there a comprehensive list somewhere of values that
the server must assign to streams?  It looks like at least the
device_id and election_id, but there may be others I am not aware of.

"The server accepts the given role.config only if the client becomes
master".  Does this mean that if a client sends a
MasterArbitrationUpdate message with a new role.id that its stream
does not already have, and it _does not become the master for this new
role_, that the stream should continue to have the old role id
associated with it?  Why shouldn't the client become a slave for the
new role id instead?

**Comment by antoninbas** [comment]
1) duplicate election id
Each stream RPC is a long-lived object. The method (https://github.com/p4lang/PI/blob/master/proto/server/pi_server.cpp#L429) will not return until the connection stops, which means that a controller is considered connected / online as long as the RPC is alive. When the stream RPC is initiated by the client, the method is called. In my reference implementation, I update a map where I insert the election id (among other things). If a new RPC comes in (either from a different client or the same client) advertising the same election id, the RPC will exit immediately with an error, stating that the election id already exists (https://github.com/p4lang/PI/blob/master/proto/server/pi_server.cpp#L472). Of course this is all partitioned by (device id, role id). Note: role id is not supported by the reference implementation at the moment.
One thing to keep in mind (I don't know if it's explicitly stated in the spec, if not a PR would be great) is that a client is limited to a single stream channel.

2) state associated with stream channel
I believe it is device_id, role_id, election_id.
I also keep a connection_id which is unique across all connections but I don't think I'm using it at the moment.
Feel free to submit a patch if you feel this is not clear enough.

3) the quote is about "role.config" and the question is about "role.id", so I'm not sure what to say.
If a client advertises a new role.id it will be moved to the new role (as a master or slave). But if the client advertises a new role.config, the precondition is that the client be a master for the appropriate role.id. You cannot modify the role.config for a given role.id if you are not the master for that role.id.

**Comment by jafingerhut** [comment]
OK, I am thinking about a PR to mention this point: "One thing to keep in mind (I don't know if it's explicitly stated in the spec, if not a PR would be great) is that a client is limited to a single stream channel."

So I think that sentence as stated might be misleading.  For example, we definitely want to allow a single process running on a single machine to have P4Runtime sessions, as a client, with many devices, whether those devices are managed by distinct P4Runtime servers, or even if some pairs of those devices are managed by the _same_ P4Runtime server, true?

Is the intended restriction something like this?  "From the perspective of the P4Runtime server, every stream channel opened is for a 'different' client.  A controller process may open multiple stream channels with the same P4Runtime server, but for each (device_id, role_id) pair, a single controller process may have at most one stream channel opened."

**Comment by antoninbas** [comment]
I don't think this is accurate. A client is identified by (device_id, role_id, election_id). As a result, the same controller process may have multiple stream channels for the same (device_id, role_id) pair. I don't think there is anything preventing one controller process from acting both as master & slave by using (D1, R1, E1) and (D1, R1, E2), although I don't see the point. Please let me know if there is something contradicting this in the spec.

So in my original sentence, client actually means (device_id, role_id, election_id).

**Comment by jafingerhut** [comment]
Closing this issue, as I believe this PR https://github.com/p4lang/p4runtime/pull/155 addresses all of the questions I had in this issue, and probably more.
