### ISSUE TITLE
Reasonable to have a table summarizing P4_16 annotations introduced in P4Runtime spec?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#106]
I think this might be a complete list of P4_16 annotations introduced in the P4Runtime spec:

+ @controller_header
+ @id 
+ @p4runtime_translation

(I grep'd the .mdk source file for `@a` through `@z` looking for unique names, so very like this is complete)

The PSA and P4_16 specs have tables / sections that give complete lists of annotations that they introduce, and I think something similar might be nice to have in the P4Runtime API spec.  I can create a PR for this if you like.  If you have any suggestions on where in the document you think it belongs, I am very open to suggestions there.

**Comment by antoninbas** [comment]
It could be nice to have such a table. Maybe you'd like to include `@brief`, `@documentation` and `@pkginfo`: even though they are not P4Runtime-specific, they do impact P4Info generation. See @chrispsommers PR: https://github.com/p4lang/p4runtime/pull/103

Maybe you could add it in an appendix?

**Comment by chrispsommers** [comment]
@antoninbas @jafingerhut Good ideas, I plan on moving the PR to a branch instead of a fork and incorporating Antinin's feedback.

**Comment by jafingerhut** [comment]
Sure I can create a PR that adds such a list/table in an appendix.
