### ISSUE TITLE
Section 6.4.1 UNSPECIFIED enum value should be removed from spec?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#108]
The spec mentions the 2 enum values that are in the .proto file, but also a 3rd one called 'UNSPECIFIED' that is not in the .proto file.  Should that be removed?  Or perhaps that 3rd possibility is intended to say that if the message leaves out a value for `idle_timeout_behavior` completely, the meaning is not defined?  If the latter, it might be better to word things differently there to make that clear.

**Comment by antoninbas** [comment]
The spec needs to be updated. We removed 'UNSPECIFIED' as a possible enum value a while back, as it made more sense to have the default value be "no idle timeout support". I saw another typo I have to fix in the spec, so I can take care of this one as well.
