### ISSUE TITLE
Section 6.4.3 table_ids is redundant info?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#109]
It seems like the value of table_ids could be calculated from the contents of all table definitions in the rest of a P4Info file.  Why bother specifying such redundant information, when it seems that the only purpose in having it there is to cause some P4Info files to be incorrect, because the redundant info is inconsistent with the rest of the file, and it is easy calculatable with a linear time pass over all table definitions?

**Comment by jafingerhut** [comment]
Same question for the direct_table_id field of a DirectCounter and DirectMeter objects.

**Comment by antoninbas** [comment]
I agree that this information is redundant and I don't believe I personally heavily rely on it in my code. I do access it when I parse the P4Info to instantiate some other data structure, but as you mention that could be replaced by a linear search.

However, at this stage I don't believe it is worth the trouble to try and remove it. We would need to give a heads up to the various stakeholders. Hopefully at this stage the p4c compiler populates these fields correctly, and it will not be too much of a burden for other potential generation tools.

**Comment by jafingerhut** [comment]
OK.  No actual trouble leaving it in there for me, either.  Closing this issue.
