### ISSUE TITLE
Bytestrings representation of negative `int<W>` type values

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#111]
I do not see how the examples of signed int<W> values can possibly
achieve the goal of "It helps facilitate non-disruptive P4 program
updates".  It seems to me that a way to achieve that would be to
mandate that any extra "padding" most significant bits are copies of
the sign bit, i.e. 0 for non-negative values, or 1 for negative
values.  If you do not do that, then a client sending a 0-padded
int<12> negative value to a server that expects an int<13> will
interpret it as a non-negative value.

Given that int<W> type values are typically much rarer than bit<W>
type values, I don't think this is urgent to correct before a
P4Runtime spec v1.0 release.  It does seem important to address some
time.

**Comment by antoninbas** [comment]
It does seem important to address this before the release, even if it is to say that the scheme doesn't work with signed values and update the examples. I'll think some more about the sign-extension but don't hesitate to open a PR if you've given it some thought :)

**Comment by jafingerhut** [comment]
You are welcome to assign this one to me.  I have some thoughts on the topic that might be useful.  Nothing too exciting -- the basic idea is simply that for `int<W>` values, whenever they are "padded" to a larger bit width for transmission, they should always be padded with copies of the sign bit, not always 0 like unsigned values are.  Adding more most significant bits equal to '1' at the beginning of a 2's complement negative value preserves its numeric value.

**Comment by jafingerhut** [comment]
Antonin, does the P4Info file specify whether a value is of type `bit<W>` vs. `int<W>`?

If it does, then I can see a way to change the specification to do what I was hoping to do.

If not, then I don't see how to specify things so that `int<W>` values can be transmitted between a client and server, and allow them to have different bit widths, _and_ still use 2's complement representation as the binary format.

**Comment by antoninbas** [comment]
Yes, it's a different oneof case when it is a `bit<W>` vs an `int<W>`: https://github.com/p4lang/p4runtime/blob/master/proto/p4/config/v1/p4types.proto#L92

**Comment by jafingerhut** [comment]
@antoninbas Thanks for that pointer to the file p4types.proto, but I don't see any way for a client to tell from a P4Info message contents whether an action parameter or table key field is `int<W>` or `bit<W>`.  Am I missing a way to distinguish that?

**Comment by jafingerhut** [comment]
Created PR https://github.com/p4lang/p4runtime/pull/128
