### ISSUE TITLE
Confusing wording of a sentence in section 8.5.2

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#112]
8.5.2. P4 Type Specifications in p4info.proto

In this sentence:

    "P4DataTypeSpec is meant to be used in P4Info, everywhere where
    the P4Runtime client can provide a value for a P4_16 expression."

should "value" be replaced with the word "type"?  It seems like the
message "P4Data" is intended for conveying P4_16 values, isn't it?

**Comment by antoninbas** [comment]
what about this:

> P4DataTypeSpec is meant to be used in P4Info, to specify the expected format of the P4-dependent values being exchanged between the P4Runtime client and server. Each P4DataTypeSpec message corresponds to a compile-time type in the original P4_16 program (e.g. the type parameter of an extern).
