### ISSUE TITLE
Possible to read only a "match anything" table entry from a table?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#115]
I guess the first question is: if a table has no fields with match_kind 'exact', is it possible via P4Runtime to add an entry that is don't-care for all fields, that is _not_ the default entry?  If so, does it do so by doing an INSERT with no match repeated fields at all, and is_default_action=false?

If that is allowed, then it seems like there is no way to read _only_ that entry from the table, because if you provide no match fields in a table read request, it will read _all_ table entries, yes?

If so, that doesn't seem like a terrible restriction.  Mainly wanted to check my understand of the above questions here.

**Comment by antoninbas** [comment]
I believe you are correct. However, note that the priority is always taken into account when reading entries, and 0 is not a valid priority for a ternary match. Therefore, you would not end up reading *all* table entries, but only the table entries with the given priority. If the client uses distinct priority values for all entries (which I believe is good practice), you will end up with a single entry.
However, it may be worth mentioning this limitation in the spec.
