### ISSUE TITLE
Weaken wording regarding idle timeout notifications?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#117]
Section 9.1.6 Idle Timeout

Consider replacing "must" with "should" in the phrase "the
P4Runtime must generate a stream notification".  "must" seems to imply
that an implementation can guarantee it will send such a message, but
this seems impossible to guarantee for most reasonable-cost
implementations, e.g. a table with 1 million entries has an idle
timeout of 1 millisecond for all entries, and no packets match any
entries for a long time.

Same comment for this phrase where it occurs in Section 16.4 "Table Idle Timeout Notification"

**Comment by antoninbas** [comment]
Is this the same as #116 ?

**Comment by jafingerhut** [comment]
Yes, closing this one.  Must have fat-fingered the creation of the earlier issue and accidentally created two of them.
