### ISSUE TITLE
Is it (and should it) be possible to configure multiple table entries with same one-shot?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#120]
Reading over Section 9.2.3 "One Shot Action Selector Programming", it appears that one can use that technique to create one table entry that "points at" a group created via the same message request, but there is no 'group id' visible to the controller software created, and thus no way to make a second table entry "point at" the same group?

I thought that was a use case that @konne-google intended to be possible using the one shot action selector programming?

e.g. can I create a group using the one shot action selector programming, then add 100 entries to a table that all point at the same group, then update the group contents via another one shot action selector message?

Or is that only possible via using the explicit member id / group id messages?

I am personally fine either way.  I just have half a recollection that the intent of the one shot was to continue to make group ids explicit to the controller.

**Comment by antoninbas** [comment]
That is essentially why we are keeping the member id / group id messages around.
Being able to share groups across match entries was not one of the pre-requisites IIRC. And @konne-google wrote that section himself :)
Being able to re-use the same group would mean re-introducing some indirection. True, there is a 3rd alternative programming method that we didn't include in P4Runtime (with indirection for groups, but not members), but I think we can do without it.

**Comment by jafingerhut** [comment]
@stefanheule Not sure if you have any knowledge or thoughts on these questions, but wanted to ping you, given your close following of recent issues on the P4Runtime spec.

**Comment by stefanheule** [comment]
I don't, but I sit next to Konstantin, I'll make sure he takes a look at this today so we can move forward.  Thanks for keeping an eye on this.

**Comment by konne-google** [comment]
Yes this is completely as intended. There is a one-to-one mapping between groups and flows with oneshots. We still need indirection, but we model it explicitly by matching having the flow perform an exact match on a "wcmp" id which is set by a previous LPM table. So there can be multiple flows in that LPM table referring to the same group by setting the same "wcmp" id.

**Comment by jafingerhut** [comment]
@konne-google That makes sense to me now, and I probably should have thought of the scenario you mention -- one table like LPM on IP dest address that contains a metadata field like "wcmp_id" that is then used as the search key for a later table with the one-shot action selector.  Thanks for the response.
