### ISSUE TITLE
Possible small exception to WriteRequest idempotency?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#122]
12. Write RPC

"The Write RPC is idempotent, i.e. multiple invocations of the same
RPC do not have any side effects."

I think I understand the intent here, but as maybe an insignificant
case that sounds like it doesn't quite follow that statement would be
multiple MODIFY operations that assign a value to a counter entity.
The first one could assign a value to the counter, the data plane
could update it several times, then the second MODIFY would have the
side effect of writing the counter back to the old value.

**Comment by jnfoster** [comment]
I think this is probably fine. Two writes without intervening data plane
operations are still idempotent... Maybe we should say that?

**Comment by jafingerhut** [comment]
Created PR https://github.com/p4lang/p4runtime/pull/129 using Nate's suggestion.
