### ISSUE TITLE
Another possible note for somewhere in Section 17.1 "PSA Metadata Translation" ?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#131]
If the following is explicitly planned _not_ to be supported in P4Runtime API version 1.0, it seems maybe worth mentioning somewhere in the spec:

+ Using a value with numeric runtime translation (e.g. PortId_t) as an index to a register, indexed counter, or indexed meter.

If it is planned to be supported, that also seems worth mentioning, but at least right now there doesn't seem to be anydata in the P4Info file that could indicate the type of the index.

**Comment by antoninbas** [comment]
I'm torn about this issue. On the one hand, this seems like an important thing to support (I have seen many programs indexing a register or a counter with the port id). On the other hand, I don't see any easy way to support it. We would need to add some flag in P4Info to indicate that the index is actually a translated value...

**Comment by jafingerhut** [comment]
It certainly seems reasonable to me to postpone support of such things until after P4Runtime API v1.0 is released, if that helps you become un-torn :-)
