### ISSUE TITLE
Bytestring length rules and upgrade compatibility issues

### ISSUE THREAD

**Issue by teverman** [p4lang/p4runtime#14]
Under "General principles for message formatting" in the "Bytestrings" subsection, the server is required to return an error if the P4Info-defined bitwidth, rounded to bytes, is not equivalent to the bytestring length in the P4Runtime message.  Enforcement of this requirement leads to awkward upgrade constraints.

Suppose a match field X exists, and X has a P4 program specified width of 9 bits.  Now suppose a new version of the P4 program changes the width to 10 bits.  Since the client and server are likely to upgrade at different times, a 10-bit-aware server will accept requests with a 9-bit X from an older client.  Similarly, a server expecting a 9-bit X will accept client requests with a 10-bit X, subject to the constraint that the client cannot use the full range of X until the server also upgrades to the P4 config with 10-bit X.  The same thing holds if X expands to 11, 12, 13, 14, 15, or 16 bits.

Unfortunately, if at some time X needs to expand to 17 bits, compatibility issues between client and server arise.  If the server upgrades first, it must reject any X from old clients that continue to send X as 2 bytes in a P4Runtime request, even though the request value fits within the P4Info-specified width of 17 bits.  The (p4_bitwidth + 7 / 8) computation will yield an expected byte size of 3 on the server, but the older client will be sending a string of 2 bytes, leading to an INVALID_ARGUMENT error from the server.

As shown above, the current byte string size requirement leads to an anomaly where expansion of bitwidths can occur gracefully across client and server versions as long as the expansion does not cross byte boundaries.  However, once that boundary is crossed, it becomes difficult to gracefully roll out new versions of the P4 program.

An improved approach would require the server to assure that the bytestring provided by the client translates to an integer value that fits within the specified bitwidth.  The server is free to accept bytestrings that appear to be padded with leading zeroes.  The server can also accept bytestrings that omit leading zeroes.

**Comment by antoninbas** [comment]
I think we should discuss this at the meeting next Wednesday.

That seems reasonable to me, but I think the rationale for restricting the size of the value to the byte-width of the P4 field was to ensure we had a canonical representation for these values. We would lose that with this proposed change. AFAIK, the canonical representation was to guarantee read-write symmetry without necessarily having to store all the proto messages at the server.

**Comment by teverman** [comment]
Agree on a meeting discussion.

The requirement to encode the field in a bytestring with length
(p4_bitwidth + 7 / 8) at the sender can persist, with the receiver free to
infer 0-byte padding for leading bytes or discard unexpected leading
zeroes.  Read/write symmetry is retained as well as it was before.  Keep in
mind that the existing scheme also has a potential read/write symmetry
problem during upgrade transitions.

**Comment by antoninbas** [comment]
The decision at the 01/08/2018 P4 API WG meeting was to relax the constraints on the bytestring format, while defining a canonical representation to preserve (or rather fix) Read-Write symmetry.

The canonical representation will be the shortest string that fits the integral value. The server will continue to accept padded values for backward-compatibility. If the integral value doesn't not fit in the P4Info-specified bitwidth, the server will return an error (`INVALID_ARGUMENT` or `OUT_OF_RANGE`?).

A patch will be submitted soon to modify the spec accordingly.
