### ISSUE TITLE
Section 9.1.2 "Action Specification"

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#140]
This sentence seems wrong: "The `Action` Protobuf message, which is used for direct tables only, has the following fields:"

because the `Action` Protobuf message is also used for tables within action profiles and action selectors, too?

Or perhaps the statement is meant as "which is used as the `oneof` choice, among those available in a `TableAction` message, only for direct tables" ?

**Comment by antoninbas** [comment]
You're correct. This statement stopped being true when we added the oneshot programming method for indirect match tables with selectors.
