### ISSUE TITLE
P4HeaderStack messages and the size of the P4 program's corresponding header stack variable

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#141]
It seems reasonable that everything is fine if a P4HeaderStack message has the same number of headers in it as the maximum number of headers declared in the P4 program -- the first header in the message should correspond to element 0, the next element 1, etc.

If the message has more than the P4 program's maximum size for the header stack, is that an error?

If the message has less than the P4 program's maximum size for the header stack, is that an error, or should the message's header stack value be appended with enough invalid headers at the end of the header stack (i.e. the largest index values)?

The P4Info file seems to have no explicit representation of header stacks, and no way for the control plane to know what the maximum allowed size of a particular header stack is.

Same issues/questions exist for stacks with elements that are header_union.

**Comment by jafingerhut** [comment]
I personally consider this issue fairly low priority, as the only way it is relevant in P4Runtime v1.0 is if someone has a P4 program where a Register extern has a header stack as one of its elements stored in each register array element, which seems like an unusual use case to me.

**Comment by antoninbas** [comment]
Actually the P4Info does have the max size information I think (https://github.com/p4lang/p4runtime/blob/master/proto/p4/config/v1/p4types.proto#L147). But it may be a good idea to specify what is expected from the P4Runtime client. I am tempting to say that the client should provide a "value" for each element of the stack, but we can also support providing fewer values, because headers & header unions have the notion of validity.

**Comment by jafingerhut** [comment]
Huh.  Not sure how I missed the max size information, but yes it is there.

If we want to preserve read-write symmetry here, one way would be to require that all N headers are specified in the message explicitly.  The other would be that all of the "last" invalid headers should never be present in the message (in the read-write symmetry form, at least).

Another detail with read-write symmetry and P4HeaderUnion is probably that it should be required that invalid header_union values must have valid_header_name equal to the empty string and valid_header unset.
