### ISSUE TITLE
Why does MasterArbitrationUpdate have explicit field with type google.rpc.status?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#142]
This section in the Madoko source "# Error Reporting Messages { #sec-error-reporting-messages}" begins with this statement:

"P4Runtime is based on gRPC and all RPCs return a status to indicate success or failure."

If so, why does the MasterArbitrationUpdate message have a field of type google.rpc.status?  If the statement above is true, then it seems one of the statements below follows:

+ MasterArbitrationUpdate can only appear in a channel that is defined to be 'stream' in both directions between client and server, and thus the phrase "all RPCs" above is not applicable to any such messages, i.e. such messages do _not_ automatically return a status to indicate success or failure, and thus one must be explicitly defined if we want to the server to be able to send such a value in the response message back to the client.

+ The field is redundant, and could be removed.

but I could be missing some other possibility.

As an aside, why the "." before the type ".google.rpc.status" in the p4runtime.proto file definition of this field?

**Comment by antoninbas** [comment]
This field is *not* used to indicate success or failure of the streaming rpc. It is used to signal to the client its mastership status. In theory, this field could be replaced by a simple boolean / enum value AFAIK, but using `google.rpc.Status` lets us include a human-readable message. Just because a client receives a non-ok status (indicating it is not master, or no longer master) doesn't mean the RPC failed. Returning an error status with gRPC would actually terminate the streaming RPC, which is not desired behavior here.

**Comment by antoninbas** [comment]
I don't know about the leading `.`. I imagine it is to indicate that the name is fully-qualified, just like a leading `::` in C++.

**Comment by jafingerhut** [comment]
So is it true that the statement "P4Runtime is based on gRPC and all RPCs return a status to indicate success or failure." could be accurately reworded as the following?

"P4Runtime is based on gRPC and all _unary_ RPCs return a status to indicate success or failure."

A ReadRequest is a single message that has a repeated field of desired Entity's to read.  The ReadResponse is in a stream.  There are some erroneous kinds of ReadRequest messages for which the server is specified that it should return an error status.  Would such an error status break the return stream, leading in some cases to only a partial collection of read responses sent back to the client?

**Comment by antoninbas** [comment]
No the original statement is correct. All RPCs in P4Runtime return a status to indicate success or failure. If the client sends an invalid message on the stream, the server will terminate the stream prematurely with an error. For example, in case on an invalid device id: https://github.com/p4lang/PI/blob/master/proto/server/pi_server.cpp#L462. The status field in `MasterArbitrationUpdate` is not used to indicate success or failure.

For read response, we would not really break the stream I believe. We would attempt to read all entities. If there is a failure at some point, we will keep reading and save all the errors for the end. So we wouldn't interrupt the stream prematurely in general. We would save the error for the end. Unlike the StreamChannel, a read Stream has an "end". I think 13.3 covers that.

**Comment by jafingerhut** [comment]
All of this sounds reasonable to me.  I cannot think of anything to change in the spec regarding this issue, so closing it.
