### ISSUE TITLE
Is election_id allowed to be the same for different controllers?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#149]
A more full statement of the question:

Suppose a single server has multiple devices (say 3 for example, numbered with device_id values 101, 102, and 103), and each of its devices has 2 roles (numbered with role_id values 201 and 202).

Suppose we have 2 controllers, C1 and C2.

Is it allowed that controller C1 can use election_id 42 for (device_id=101, role_id=201), and at the same time controller C2 can use election_id 42 for (device_id=101, role_id=202) ?

In general, can the same election_id be used by different controllers for different (device_id, role_id) value pairs?

Right now the spec says:

"Each controller is assigned a `role_id` and an `election_id`. The `role_id`
  defines the role (or realm) that the controller is part of. The `election_id`
  is unique per role and identifies the master for a specific role. At any point
  in time, the controller with the largest `election_id` for each role is the
  master and the rest are slaves."

It is not clear whether election_id's are required to be unique for each role_id value in a single server, or whether they are merely required to be unique for each (device_id, role_id) pair in a single server.

**Comment by antoninbas** [comment]
Yes, only the `(device_id, role_id, election_id)` tuple is required to be globally unique. The way I see it, `(device_id, role_id)` identifies a set of "dataplane elements". All the controllers for that set need to be identified by a unique election id, but all sets are managed completely independently.

Devices are actually uniquely identified by their device id, whether on the same server / chassis or not.

The only case where having unique election ids may be useful is if a controller wants to be able to control an arbitrary set of "dataplane elements" with the same election id. But the burden is on the orchestration system which manages controller instances.

I can imagine building a basic replicated control plane where I would only use 2 election ids (one always meaning slave, one always meaning master), which would be the exact same for every `(device_id, role_id)`. Although that's hardly how the consensus protocols used to assign these election ids work in practice.

Maybe @teverman or someone who is used to using an arbitration scheme in production can confirm.

**Comment by jafingerhut** [comment]
OK, created a PR that might be useful in clarifying some of this: https://github.com/p4lang/p4runtime/pull/150

**Comment by teverman** [comment]
I suppose it would be possible to have scenarios where the arbitration
mechanism is different according to role.  In Andy's original scenario, the
arbitration scope for role_id's 201 and 202 could differ, and thus C1 and
C2 could end up with the same election_id for one or both of the roles.

Tom

**Comment by jafingerhut** [comment]
So I think this statement is accurate: For all simultaneously active StreamChannel's maintained by a single P4Runtime server for which a (device_id, role_id, election_id) tuple is assigned, every one must have a (device_id, role_id, election_id) that is different than all others.

Aside: StreamChannel's are expected to be created, and at least for a brief time will not yet have such a value assigned to them.  They are not included in the above statement.

If device_id values are unique among all devices in a collection of P4Runtime servers, then that statement can of course be generalized from "a single P4Runtime server" to "the collection of P4Runtime servers under consideration".

There seems to be the potential for confusion in talking about clients and controllers that they are different names for the same thing, which I am not sure they are.

In some places of the spec, or these discussions on these Github issues, it sounds like there is a one-to-one relationship between "client" and "an StreamChannel with a (device_id, role_id, election_id) assigned to it".

However, if you think of a client as "a process, which might have multiple active StreamChannel's, to one or more P4Runtime servers", then there is definitely then a one-to-many relationship between clients and active StreamChannels.

Similarly for the word "controller".

Is there a particular use of the words "client" and "controller" that you want to stick to in the P4Runtime spec?  If so, should it be the meaning with the one-to-one relationship with active StreamChannels, or the meaning with the possibly one-to-many relationship with active StreamChannels?

**Comment by jafingerhut** [comment]
Another issue that has some overlap with this one, for reference: https://github.com/p4lang/p4runtime/issues/105

**Comment by jafingerhut** [comment]
I guess what I am trying to say with the previous comment is that this use of the term "client" and "controller" seem somewhat at odds with common usage of "controller", which seems to commonly be used for the purpose of "an entity that controls N > 1 switches in a network"

**Comment by antoninbas** [comment]
@jafingerhut do you think we should maybe have a phone call some time this week to resolve this issue? I hope @teverman can join as well and of course anyone who is interested in this topic is welcome.

**Comment by jafingerhut** [comment]
Sure, a phone call would be good.  Feel free to send email to set up the details.  Sorry, not trying to be difficult here, but it seems good in a spec to be clear in terminology, especially if it is slightly different than common usages in the industry.

**Comment by antoninbas** [comment]
No worries, it is good to have this conversation. I think the notion of "role" is a bit new and makes things a bit challenging. I'm hoping Tom can provide some context on the scope of the arbitration scheme. Is it per `device_id`, per `role_id`, or per `(device_id, role_id)`... I'm starting to think it should be per `role_id`, and that a controller would probably want to advertise the same `election_id` for that role to all devices it is connected to, assuming these devices run the same P4 datapath.

**Comment by antoninbas** [comment]
I'll send an email to set up a call today.

**Comment by jafingerhut** [comment]
I thought I added this comment before, but I don't see it now, so must have not done it properly.  Trying again.

Note: The following text introduces the term "identity" as a name for a
(`device_id`, `role_id`, `election_id`) 3-tuple of values that a server has
accepted as valid for a `StreamChannel`. There may be a better term than
"identity" for this. Suggestions welcome.

I am using the term "stream" below, as defined in the P4Runtime specification
"Terms and Definitions" section, copied here for convenience:

* stream
  : Refers to a gRPC Stream, which is a RPC on which several messages can be
    sent and received. P4Runtime defines one Stream RPC (`StreamChannel`), which
    is a bidirectional stream (both the client and the server can send messages)
    which is used for packet I/O and master-slave arbitration, among other
    things.


For a single P4Runtime server:

+ It manages one or more devices, each with unique `device_id` values.

+ Every device has at least one `role_id`. There is a default `role_id` of 0 if
  a `role_id` is not set in a `MasterArbitrationUpdate` message. The role with
  id 0 has full write access to all entities of the device. A device may have
  multiple `role_id` values, chosen by a mechanism not defined in the P4Runtime
  API spec. For example, a particular P4Runtime server may use annotations in
  the P4Info file to decide which entities are writable by which roles.

+ At any given time, there can be 0 or more `StreamChannel` streams that have
  been created.

  + Typically, most of them will have configured a (`device_id`, `role_id`,
    `election_id`) tuple of values via the client sending a
    `MasterArbitrationUpdate` message. Call such a 3-tuple of values the
    stream's "identity". A stream can have at most one identity associated with
    it at a time. The identity of a stream can change over time, if the client
    sends appropriate `MasterArbitration` update messages to the server, on that
    stream, to change the identity. That is the _only_ mechanism by which a
    stream's identity can change.

    Call two identies equal if they have equal numeric values for all 3 of their
    integer values in the 3-tuple, otherwise they are different.  Every
    P4Runtime server maintains invariant (I1):

    (I1) Among all streams established at a single P4Runtime server that have
    identities, those identities are unique.

  + There could be one or more streams where no `MasterArbitrationUpdate`
    message has been sent by the client. These streams have no identity
    associated with them.

For a complete network of P4Runtime servers, it is desirable to maintain
invariant (I2):

(I2) All `device_id`'s are unique throughout the network.

(I2) is useful when writing controller software that manages multiple
devices. Below, we will only consider networks that satisfy (I2).

Any network satisfying both (I1) and (I2) also trivially satisfies (I3):

(I3) Among all streams with identities, established among all P4Runtime servers
in the network, those identities are unique.

A "controller" is a system, e.g. a process running on a single computer, that
can have 0 or more established streams with one P4Runtime server, or many
P4Runtime servers.

Note that if "controller" is defined in this way, then sentences like the
following sound confusing to me:

* Each controller is assigned a `role_id` and an `election_id`. The `role_id`
  defines the role (or realm) that the controller is part of. The `election_id`
  is unique per role and identifies the master for a specific role.

It sounds confusing to me because when I think of a controller as defined above,
I should be able, if I choose, to write controller software that has multiple
streams established, some of which have identities with different `role_id`
values from each other. For example, a single controller might simultaneously
have the streams created with identities `(device_id=1, role_id=101,
election_id=50)` and `(device_id=2, role_id=150, election_id=7005)`. If that is
intended to be allowed, then the sentence "Each controller is assigned a
`role_id` and an `election_id`" sound unnecessarily constraining on what kinds
of controllers can be created.

Instead, something like the below, while maybe not terribly specific, seems
possible to be true in a distributed system:

* For each `(device_id, role_id)` with which a controller wishes to establish a
  stream, the controller must obtain an `election_id` value such that all
  `(device_id, role_id, election_id)` identities in the network are unique. A
  controller is allowed to establish streams with as many unique identities as
  the developers of the controller software wish, subject to the constraints of
  the invariants. As a possibly unusual example, a single controller could
  create multiple streams with the same `(device_id, role_id)` values, but
  different `election_id` values (although it is not clear if that is a useful
  thing to do).

**Comment by antoninbas** [comment]
Based on the P4 API WG meeting discussion today (01/16/2019), I would recommend replacing the confusing sentence that triggered this issue by something like:

> “Each controller instance (e.g. controller process) can participate in one or more roles. For each role, the controller receives an election_id, which may be the same across multiple roles. The controller advertises its (role_id, election_id) tuple to each device that supports this role, so that the device can pick a master (the controller instance with the highest election_id). A connection between a controller instance and a device id - which involves a persistent StreamChannel - can be referred to as a P4Runtime client.”

If controller is used in a confusing way somewhere in the spec, we can clarify by using "controller instance" instead.

@jafingerhut would you mind updating your PR if needed and assigning @wmohsin as a reviewer?

**Comment by antoninbas** [comment]
Sorry for the phrasing. Yes, it is what I meant by advertise (send a MasterArbitrationUpdate message).

**Comment by stefanheule** [comment]
One more comment for that paragraph: It makes it sound like every controller instance has a single election_id that is used across all devices, but this is not necessarily true (at least I don't think we want to make any such restrictions).  Instead, a controller is free to use different election_id's for different stream channels, or use the same one, as long as the (device_id, role_id, election_id) tuple stays unique.

Maybe a better replacement would be something along the lines of:

> Each controller instance (e.g. controller process) can participate in one or more roles and with one or more devices. For each role and device, the controller picks an election_id (typically through a leader election process outside of P4Runtime).  This election_id can be the same for different roles and/or devices, as long as the tuple (role_id, device_id, election_id) is unique.  The controller establishes a StreamChannel with the P4Runtime server for the device and sends a MasterArbitrationUpdate message containing (role_id, device_id, election_id).  This allows every device to uniquely identify the master for every role (the streaming channel with the highest election_id). A connection between a controller instance and a device id - which involves a persistent StreamChannel - can be referred to as a P4Runtime client.

This also brings back the mention that the election_id needs to be picked using a scheme that's outside of P4Runtime.

**Comment by antoninbas** [comment]
Sounds good to me. It is true that we do not want to add this restriction, although it is unlikely that there will be an election process per device.

**Comment by stefanheule** [comment]
I agree, though I could see someone using an election process per role.  It was unclear if that was allowed or not.

**Comment by stefanheule** [comment]
And reading the spec one more time, it has the sentence "To support multiple controllers, P4Runtime uses the same streaming channel (available via StreamChannel RPC) for session management. The workflow is described as follows:".  What is the "same" referring to here?  As far as I can tell, this is the first time we mention the streaming channel, so it's not referring to a different use of the streaming channel.  It also can't mean *the same channel for all controllers*, because that wouldn't make any sense.  Can we drop "same"?  Or maybe I'm just misunderstanding.

**Comment by antoninbas** [comment]
* yes the intent was definitely to express that the election id can be different between roles (although you are correct that we can have granularity at the device level)
 * I believe the "same" here was meant to read "the same as for Packet IO". However, it is possible that because of some past shuffling of paragraph, this "same" is not appropriate any more and should be removed.

**Comment by stefanheule** [comment]
Okay, then I recommend we remove same, because as far as I can see this is now the first mention of the streaming channel.  We actually later (just a few bullet points later) use "same" again when introducing packet IO, so we capture that those two are using the same channel.

**Comment by jafingerhut** [comment]
I agree that the sentence is perhaps slightly less confusing without the word "same" in it, and can include such an edit in my soon-to-come updated PR.

**Comment by jafingerhut** [comment]
I will re-read my latest proposed changes a few hours from now to see if I have left anything out, and if it still makes sense to me then :-)  Please take a look at the latest diffs on this PR to see what you think.  PR: https://github.com/p4lang/p4runtime/pull/155

**Comment by antoninbas** [comment]
Fixed by #155
