### ISSUE TITLE
Meaning of is_default_action flag for table entry wildcard reads

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4runtime#160]
This concerns section 9.1.4 (Wildcard Reads) of the P4Runtime spec. The spec currently states the following:

> is_default_action: If default (false), all non-default entries from the specified table will be considered. Otherwise, only the default entry will be considered.

I kind of took this decision arbitrarily a while ago, and now I'm considering potentially changing it so that ALL entries (*including* the default entry) can be read with a single `Entity` message. But AFAIK, there is a good reason in support of both behaviors:

* why change it? Because it is potentially awkward to have to use two `Entity` messages in a `ReadRequest` to read the entire contents (match entries + default entry) of the table.

* why not change it? I sometimes use a wildcard read to query all the match entries in a table then save the response to a file. If I need to replay all the entries when restarting the switch, I just convert the `ReadResponse` into a `WriteRequest` with type `INSERT` for all updates. This works not only for tables, but also for meters, action profiles, etc. If the `ReadResponse` includes the default action, I have to be careful not to include it in the replay if the table has a *constant* default entry, or I will get an error. This introduces some asymmetry with other entities (e.g. meter).

**Comment by jafingerhut** [comment]
Perhaps it is a good time to practice what will be more strongly desired after 1.0 is released?  By which I mean, consider a change that only adds features, not changing existing ones.

In this case, keep the currently defined behavior exactly as it is, and add a new flag, or a new value to an existing parameter, that gives the other behavior.  I don't have particular suggestion for how to encode this, but one way would be a new boolean flag, of course.

**Comment by antoninbas** [comment]
At the 01/16/2019 P4 API WG meeting, it was decided to keep the current behavior as no option is immediately better than the other one.
