### ISSUE TITLE
Add a quick sentence in the spec about reading entries from const tables

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4runtime#162]
(tables with only static entries)

**Comment by antoninbas** [comment]
Depends on https://github.com/p4lang/p4-spec/issues/723

**Comment by stefanheule** [comment]
Can you clarify this?  What is the P4Runtime behavior w.r.t. const entries?  For instance:

- Are these included in read requests (e.g. a wildcard read)?
- What's the error message when trying to delete or modify a const entry?
