### ISSUE TITLE
Inconsistency between proto file contents and spec text on table entry priority

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#173]
In particular between these comments in the proto file about multiple matching entries with the same priority: https://github.com/p4lang/p4runtime/blob/master/proto/p4/v1/p4runtime.proto#L150-L158

and this text in the spec: https://github.com/p4lang/p4runtime/blob/master/docs/v1/P4Runtime-Spec.mdk#L2391-L2396

IIRC, the text in the spec is more up to date, and perhaps the comments in the proto file should be updated.  Updating the comments simply to say something like: 'See Section "TableEntry" in the specification for details on multiple matching entries with the same priority value.' might be good.

**Comment by antoninbas** [comment]
Yes, the text in the spec is up-to-date. Do you mind updating the proto?

**Comment by jafingerhut** [comment]
Created this PR: https://github.com/p4lang/p4runtime/pull/174

Note: I haven't attempted to exhaustively review all comments in the proto files to see if they match the spec, but I have not happened to notice any other mismatches yet.
