### ISSUE TITLE
Should `Metadata` message in P4Info contain a `type_name` field?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#187]
The `MatchField` messages, and the `Param` message inside of an `Action` message, both have `int32 bitwidth` and `P4NamedType type_name` fields, where the `type_name` field is used if the P4_16 program defines a custom `type` for a table search key field (`MatchField`) or action parameter (`Param`).

The `Metadata` message inside of a `ControllerPacketMetadata` message has a `int32 bitwidth` field, but no `P4NamedType type_name` field.  I believe the intent is that user-defined metadata fields in Packet-In and Packet-Out messages could also have custom `type` definitions, e.g. `PortId_t`.

Should we add a `type_name` field inside of the `Metadata` messages for this purpose?

**Comment by antoninbas** [comment]
That's correct. Without this field, there can be no translation for metadata fields in Packet In / Out messages. We should add it for the 1.0.1 release.

**Comment by jafingerhut** [comment]
Created a PR for it already, in case your answer was "yes".

**Comment by jafingerhut** [comment]
Closing issue, since relevant PR was merged.
