### ISSUE TITLE
Support the data-plane event subscription function

### ISSUE THREAD

**Issue by dingrui37** [p4lang/p4runtime#196]
**This is to suggest improvements to the `P4Runtime` specification. For issues regarding a specific implementation, please open an issue with the appropriate repository (e.g. https://github.com/p4lang/behavioral-model or https://github.com/p4lang/PI for bmv2).**

Hi all, I think if P4Runtime support event subscribe,  the data consistency between control palne and data plane can be well ensured. The schematic diagram is as the follow.
 
![image](https://user-images.githubusercontent.com/22718365/55046429-93f53c00-507c-11e9-9584-eff78aceaa13.png)

**Comment by jafingerhut** [comment]
P4Runtime provides an error status return for every write request sent from, in your diagram, the "App" to "P4Runtime".  As long as the "App" pays attention to these error return statuses, it can know what succeeded to go in, vs. what failed.

**Comment by dingrui37** [comment]
@jafingerhut If some one delete an entry by mistake, for example manually,  if this happens on the data center network, the consequences will be very serious, so we need to design a monitoring or  recovery mechanism similar to the above diagram. 
On the other hand, what if the normal write fails? Who will trigger the retry?

**Comment by jafingerhut** [comment]
If a normal write fails, the App will get an error status, and it can be programmed to respond to that in whatever way the App writer chooses.  Note that in some cases, a failure might not be transient, but that adding a particular table entry will continue to fail repeatedly, no matter how many times you try, e.g. because the table is full.  Automatically retrying in such a case is a waste of time.

**Comment by antoninbas** [comment]
You don't provide a lot of context in your question, but I think I know what you are alluding to. The burden of reconciliation is placed on the controller, which can perform periodic Read RPCs to ensure state consistency between the switch & control plane. I believe the ONOS controller reads the entire state every ~30 seconds.
All P4Runtime Write RPCs are synchronous, so the master controller knows when the RPC completes which entries were successfully written (see CONTINUE_ON_ERROR description in the spec). We do not provide asynchronous events to standby controllers when a table is modified. If the standby controllers want to maintain their own version of the state, they need to perform periodic reads as described above. In the simplest possible scenario where you have a single (master) controller during the lifetime of the switch, this controller is in charge of writing all the forwarding state. So providing the controller handles the RPC error messages correctly, it should always be in sync with the switch, except if there is a bug of course...
You can always check out the ONOS implementation if you're interested in how they use P4Runtime, although I realize this is a large code base.
