### ISSUE TITLE
Explicitly document that servers must never concurrently perform ReadRequest and WriteRequest?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#199]
**This is for reporting issues with the specification only. If you are running into a bug with a specific `P4Runtime` implementation, please open an issue with the appropriate repository (e.g. https://github.com/p4lang/behavioral-model or https://github.com/p4lang/PI for bmv2).**

Section 12.1 explicitly allows a server to implement multiple WriteRequest operations concurrently.

Section 13.3.1 seems to imply to me that a server is allowed to implement multiple ReadRequest operations concurrently.  Corrections welcome if I am misinterpreting that.

In a recent P4 API WG meeting, it was mentioned that reads cannot happen concurrently.  If so, updating Section 13.3.1 seems like a good idea.  However, I can't think of any good reason to disallow a server from processing multiple concurrent ReadRequest operations.

It was also mentioned that a server is not allowed to concurrently execute a WriteRequest and a ReadRequest.  If that is in the spec already, I would appreciate someone pointing it out to me.  If it isn't there already, it sounds like a good addition.

**Comment by antoninbas** [comment]
For the multiple concurrent Reads, the confusion comes from me. A server is allowed to process multiple Reads concurrently. The minutes for the meeting were incorrect, so I updated them.

Section 13.3 describes how a server implementation must process a ReadRequest: https://s3-us-west-2.amazonaws.com/p4runtime/docs/v1.0.0/P4Runtime-Spec.html#sec-batch-processing. The first step is "Lock state (preventing new writes)".

**Comment by antoninbas** [comment]
Note that the p4lang/PI implementation currently serializes ReadRequests (while WriteRequests are processed concurrently). It's just a shortcut I took.

**Comment by jafingerhut** [comment]
Thanks for clarifications and pointer to existing text in the spec.

So "Lock state (preventing new writes)" also means "and lock will not succeed until any unfinished writes are complete"?

**Comment by antoninbas** [comment]
That's how I understand it. And I believe that is definitely what Waqar meant.
The read will be delayed until all ongoing writes complete, and new writes should not preempt the read but be delayed until the read completes.
Feel free to submit a clarification if you think the document would benefit from it.

**Comment by jafingerhut** [comment]
So is the required observable behavior something like the following?

(REQ1) Every `ReadRequest` message must return results as if all other `WriteRequest` messages were completely finished, or not yet started?

If that is the requirement, it seems like it would be possible for a server, for some pairs of `ReadRequest` and `WriteRequest` messages that did not access any common state in the device, to execute concurrently.  e.g. if `WriteRequest` w1 only wrote entries in table t1, and `ReadRequest` r1 only read all entries in table t2, then they could execute concurrently on the server without violating the requirement (REQ1) above.

I understand that an implementation might choose to satisfy (REQ1) by never concurrently executing a read and write request, and that is a fine way to implement it.  Just wondering if such concurrency is allowed by the P4Runtime spec, or it is intended to disallow an implementation from doing so.

**Comment by jafingerhut** [comment]
I think a shorter way of asking my previous question is: "Is the requirement on the observable behavior of a P4Runtime server be that it responds to all requests in a way that is linearizable?"

**Comment by antoninbas** [comment]
From the point of view of the controller issuing read requests, definitely. From the point of view of packet processing, I don't think request handling is linearizable, since write requests can be processed in parallel if the HW allows it.

**Comment by jafingerhut** [comment]
During 2019-May-22 P4 API work group meeting, I took the AI to create a small PR that explicitly says that this is the requirement for ReadRequest results returned from a P4Runtime server:

(REQ1) Every ReadRequest message must return results as if the following were true: for every other WriteRequest message w, either w is completely finished, or w has not yet started being processed.

Also I will probably add that while this can be implemented quite easily by a server that processes all ReadRequest and WriteRequest messages at most one at a time (i.e. none of them are processed concurrently), it is likely that many systems would perform better if multiple requests were handled in parallel, while satisfying (REQ1).  For example, if there is a large batch WriteRequest updating a few thousand routes in one table, being able to satisfy another small WriteRequest on a separate table that helps implement a fast reroute mechanism, without waiting for the large batch WriteRequest to complete, is very useful.

**Comment by jafingerhut** [comment]
Proposed PR here: https://github.com/p4lang/p4runtime/pull/209
