### ISSUE TITLE
P4runtime Packet I/O details

### ISSUE THREAD

**Issue by KB00100100** [p4lang/p4runtime#201]
Hello all, I am a newbie about the P4runtime Packet I/O. Recently, I tested the official P4 program (mytunnel.p4), run the program at a BMv2 switch. During the experiments, I captured the Packet-In packet using the Wireshark tool, but I got some problems about the results.

* The Wireshark results:
_0000_   00 00 00 00 00 00 00 00 00 00 00 00 08 00 45 00
_0010_   00 85 22 ea 40 00 40 06 19 87 7f 00 00 01 7f 00
_0020_   00 01 de d3 e1 5a d3 5b e8 6f 74 ee fb 82 80 18
_0030_   03 8e fe 79 00 00 01 01 08 0a 00 27 24 bb 00 27
_0040_   23 f1 **00 00 04 08 00 00 00 00 05 00 00 02 3c 00**
_0050_   **00 3b 00 00 00 00 00 05 00 00 00 00 36 12 34 0a**
_0060_   **2a** ff ff ff ff ff ff 00 00 00 00 00 01 08 06 00
_0070_   01 08 00 06 04 00 01 00 00 00 00 00 01 0a 00 00
_0080_   01 00 00 00 00 00 00 0a 00 00 02 **12 06 08 01 12**
_0090_   **02 00 11**

Regarding the results, I know the fields "ff ff ff ff ff ff ... 0a 00 00 02" are the frame received by the switch, what I do not know is the fields "12 06 08 01 12 02 00 11" (in bold). I find anything about this in the P4runtime-spec document, does there any document to refer?

Thx!
Best regards.

**Comment by antoninbas** [comment]
What does capturing the "Packet-in packet using the Wireshark tool" mean? Packet-in messages are sent by the P4Runtime server to the client over a gRPC bi-directional stream. If you are capturing the gRPC messages, then you would naturally observe more than just the raw packet bytes. Note that the `PacketIn` Protobuf message also includes some metadata values (https://github.com/p4lang/p4runtime/blob/master/proto/p4/v1/p4runtime.proto#L513). Given that mytunnel.p4 uses the `@controller_header` annotation (https://github.com/opennetworkinglab/onos/blob/master/apps/p4-tutorial/pipeconf/src/main/resources/mytunnel.p4#L69) - which is described in the spec -, it makes sense that the serialized message would include some additional information (not just your frame). I'm sure you can make sense of those bytes by reading this document: https://developers.google.com/protocol-buffers/docs/encoding. It seems that Wireshark now comes with a gRPC dissector (https://github.com/grpc/grpc/issues/13586), maybe you can look into using that. Or, if you are using ONOS, maybe there is an option to log all P4Runtime messages to a file (in text format).

**Comment by KB00100100** [comment]
> What does capturing the "Packet-in packet using the Wireshark tool" mean? Packet-in messages are sent by the P4Runtime server to the client over a gRPC bi-directional stream. If you are capturing the gRPC messages, then you would naturally observe more than just the raw packet bytes. Note that the `PacketIn` Protobuf message also includes some metadata values (https://github.com/p4lang/p4runtime/blob/master/proto/p4/v1/p4runtime.proto#L513). Given that mytunnel.p4 uses the `@controller_header` annotation (https://github.com/opennetworkinglab/onos/blob/master/apps/p4-tutorial/pipeconf/src/main/resources/mytunnel.p4#L69) - which is described in the spec -, it makes sense that the serialized message would include some additional information (not just your frame). I'm sure you can make sense of those bytes by reading this document: https://developers.google.com/protocol-buffers/docs/encoding. It seems that Wireshark now comes with a gRPC dissector ([grpc/grpc#13586](https://github.com/grpc/grpc/issues/13586)), maybe you can look into using that. Or, if you are using ONOS, maybe there is an option to log all P4Runtime messages to a file (in text format).

Sorry for my presentation mistakes. Besides, thank you very much for your detailed and patient answer.
