### ISSUE TITLE
Include source for diagrams / figures

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4runtime#21]
So that people can edit them
Do not use images as they are kind of blurry

**Comment by chrispsommers** [comment]
I agree with this idea but it'll take some effort to redraw them. Many of the diagrams (the Ref Arch ones anyway) were created directly in gDoc to solve the "what kind of graphic editor shall we use?" question. The source could not be extracted during conversion to Madoko, so screen captures were done. To abide by a policy to include source, they all need to be redrawn from scratch in an agreed-upon tool. BTW, PowerPoint was used for PSA spec. I'd think we'd prefer to encourage an "open" tool though; PowerPoint is licensed and might exclude some potential contributors. Perhaps between PowerPoint and LibreOffice, and their flexible import/export options, we can cover all the bases.

**Comment by jnfoster** [comment]
TikZ is a really nice LaTeX-based package that can be invoked from Madoko.

It does take some time to code up each figure, but the scripting language
is fairly powerful and you can write macros to avoid having to repeat
common idioms.

The resulting figures are beautiful and don't require proprietary software
to build.

-N
