### ISSUE TITLE
What happens if the server receives a PacketOut message from a non-master controller?

### ISSUE THREAD

**Issue by pudelkoM** [p4lang/p4runtime#215]
How should the server react to such a situation? The spec just says that the controller has to be a master:

> In fact, before a controller becomes able to do Packet I/O or program any forwarding entry (via Write RPC), it needs to start a controller session and become a “master”.

I see the following possibilities, apart from ignoring the message, of course:

- Do nothing (Stratum current state)
- Log an error on the server
- Close the RPC channel with PERMISSION_DENIED (@ccascone's and my preference)

I prefer option 3 because it would match the behavior for non-master Write RPC calls:

> If the client is not the master for (device_id, role_id) according to the election_id value, the server must return a PERMISSION_DENIED error. 

It would also enforce stricter error checking and encourage defensive coding of controllers. A correctly implemented controller _knows_ that it can't send packets if it's not master. A faulty one will lose its connection, which will hopefully be noticed and corrected by the operator. Silently ignoring a permission violation seems not wise to me.

**Comment by antoninbas** [comment]
Let's discuss this at the 07/17/2019 P4 API WG meeting. Hopefully, either you or Carmelo can make it.

I think one difference is that returning `PERMISSION_DENIED` for a `Write` RPC does not kill the controller-switch connection, while closing the RPC channel essentially removes the controller from the set of standbys for the switch. Maybe that's a bit extreme. Similarly, if the master controller sends a malformed packet, should we close the RPC channel and essentially leave the switch without a mater controller?

**Comment by antoninbas** [comment]
Conclusion from the 07/17/2019 P4 API WG meeting: we are investigating adding a new field to the `StreamMessageResponse` `oneof` which can optionally be used to report errors triggered by invalid / unauthorized `StreamMessageRequest` messages.
