### ISSUE TITLE
Discrepancy between spec and proto comments, for reading direct resources

### ISSUE THREAD

**Issue by konne-google** [p4lang/p4runtime#216]
About the counter_data field in the TableEntry message, the spec says:

ReadRequest
- if unset: The response does not include the meter entry's configuration (meter_config is unset in the response).
- if set: If the meter entry's configuration is the default configuration, meter_config is unset in the response. Otherwise, the response includes the meter entry's configuration that was written by the client earlier. This respects the “read-write symmetry” principle.

However, the proto claims that resources should be returned no matter what.

Table read:
   - The counter_data field will always be set in a read table entry if the table contains a direct counter.

BMv2 appears to implement what the spec says, not what the proto says, so I would vote we update the proto :-).

**Comment by antoninbas** [comment]
You quote the spec for `meter_config` and not `counter_data`, but it seems they say roughly the same thing:

> if unset: The response does not include the counter entry's value (counter_data is unset in the response).

> if set: The response includes the counter entry's value read from the target.

I'm also in favor of updating the proto comment. I think the spec reflects the outcome of discussions within the WG.

**Comment by antoninbas** [comment]
Seems that this was actually fixed a year ago: https://github.com/p4lang/p4runtime/pull/73
