### ISSUE TITLE
Add AnnoPropertyMap containing annotation kv-pairs

### ISSUE THREAD

**Issue by chrispsommers** [p4lang/p4runtime#234]
I've found it useful to annotate P4 code with custom annotations of the form:
```
@my_anno1(a=b,c=d)
table my_table {...}
```

Where the values `b` and `d`  contain arbitrary text. I take the P4info and parse the raw annotations into a usable form. Ultimately there may be several such annotations for one entity, with multiple k-v pairs embedded in each. It would be useful to do this parsing in p4c and produce something easy to digest.

I propose something like the following. Define two new `message`s (names are arbitrary):
```
// A dictionary of strings describing something's properties
message PropertyMap {
  map <string,string> property = 1;   // key-value pairs
}

// A map of property maps (nested maps)
message AnnoPropertyMap {
  map <string,PropertyMap> propertyMap = 1;   // key-map pairs; key = annotation's tag
}
```

Then make ` AnnoPropertyMap anno_prop_map=<x>` a sibling to `annotations `in every place it appears.
Then with P4 code such as this:
```
@my_anno1(a=b,c=d)
@my_anno1(e=f)
@my_anno2(w=x,y=z)
table my_table {...}
```
you'd get raw annotations (already in P4info) like this:
```
annotations: "@my_anno1(a = b , c = d)"
annotations: "@my_anno1(e = f)"
annotations: "@my_anno2(w = x , y = z)"
```
Note: `p4c` already parses them as k-v pairs then re-serializes them with spaces around the = sign.)

The enhancement would produce a sibling to the annotations something like this (expressed as python dicts):
```
"anno_prop_map": {
   "my_anno1": {
    "a": "b", 
    "c": "d", 
    "e": "f"
  },
"my_anno2": {
    "y": "z", 
    "w": "x"
  }
}
```
The result is a set of nested maps; the outer one is keyed by the annotation tag and the inner ones by the key of each k-v pair.

Note `@my_anno1()` appeared twice in the p4 code and the k-v pairs got merged,  consistent with how p4c already merges them.

**Comment by antoninbas** [comment]
This may not need to wait until v2.0 if the proposal is to *add* a new Protobuf field in addition to the existing `annotations` field, since it would not break backward-compatibility. We can discuss it at the next API WG meeting (09/28).

**Comment by chrispsommers** [comment]
It is a new field, it should be totally backward-compatible. Thanks.

**Comment by antoninbas** [comment]
This was discussed at the 08/28/2019 P4 API WG meeting (https://docs.google.com/document/d/1qzeAnKDDOIgBzq3sLS1C1CacunTtrV5x5T5xPXUFRGM/edit#heading=h.1luy7m2zeqb), and we decided to include support for this in P4Runtime v1.1.0 if possible.

**Comment by antoninbas** [comment]
After new discussions and because of recent changes to the P4_16 language for the 1.2 release (annotations are now completely unstructured), we are postponing this for now. Further discussions are needed with the P4 language design WG (AI @chrispsommers @stefanheule):
 * can some existing annotations be standardized by the language (`@id`, `@pkginfo`,...)?
 * can new standard structured annotations be defined (`@properties` with a KV map body)?
 * what was the argument for making annotations completely unstructured and for removing KV map?

**Comment by antoninbas** [comment]
As discussed at the 10/23/2019 P4 API WG meeting, I am removing this from the v1.1.0 milestone. We will collaborate with the LDWG to reach a satisfactory solution for P4_16 v1.3.0 / P4Runtime v1.2.0. See the minutes for more details: https://docs.google.com/document/d/1qzeAnKDDOIgBzq3sLS1C1CacunTtrV5x5T5xPXUFRGM/edit#heading=h.fag17iz3x4wo

**Comment by chrispsommers** [comment]
Superceded by https://github.com/p4lang/p4runtime/issues/264
