### ISSUE TITLE
Double-check whether 1-bit signed values pose any issues for P4Runtime spec

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#244]
Action item taken by me at 2019-Oct-23 P4 API work group meeting.  I do not know of any problems yet, but will spend a little time thinking about the details and report back with any issues found, or "looks all good", in a comment on this issue.

**Comment by jafingerhut** [comment]
I have looked at the P4runtime specification and what it has to say about values with signed integer types, i.e. `int<W>` for some integer W, and whether there are any problems in the P4Runtime spec if W=1 in type `int<W>`.

The short answer is that I have not discovered any problems, and believe that no changes to the P4Runtime specification are needed for this case.

Examples of things I have checked, and see no issues with:

The P4Runtime spec contains the statement: `For a value of type int<W>, the fewest number of bits required to represent the integer value $V \neq 0$ in 2's complement form is the smallest integer $A$ such that $-2^{A-1} \leq V \leq 2^{A-1} - 1$.`.  For type `int<1>` there are only 2 legal values, -1 and 0, that a value with that type can have.  Plugging A=1 into the formulas gives the inequality `-2^0 \leq -1 \leq 2^0-1`, which simplifies to `-1 \leq -1 \leq 0`, which is true, and perfectly fine.  A=1 is the fewest number of bits that can represent a signed value of V=-1.

Just as a value of type `int<2>` has only 4 possible values: -2, -1, 0, 1, and their minimum length representations are all 1 byte long in P4Runtime, with hexadecimal representations 0xfe, 0xff, 0x00, 0x01 ...

there are only 2 possible values for a value with type `int<1>`, -1, 0, and their minimum length representations in P4Runtime as 1 byte long hex strings are 0xff, 0x00.

**Comment by jafingerhut** [comment]
I also tried out a recent version of the open source p4c compile with a register whose elements had type `int<1>`, and it seems to produce the correct P4Info file.  See the attached .zip file for my test program and the P4Info file that p4c generated, if you are curious.
[p4runtime-issue-244.zip](https://github.com/p4lang/p4runtime/files/3764200/p4runtime-issue-244.zip)

**Comment by antoninbas** [comment]
Thanks for checking this @jafingerhut. That is consistent with what I remember from the spec. I will close this issue to mark it as resolved towards the v1.1.0 milestone.
