### ISSUE TITLE
Find a more "automatic" way to manage references

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4runtime#25]
It would be great to have a less manual way of doing this (no repeat of the link, in-order numbering)
I don't know if there is a convenient way to do it in Madoko, maybe we can abuse the bibliography support.

**Comment by antoninbas** [comment]
Thanks, but that's not really what we wanted to do. We would still like to have a reference section at the end with a list of links and number values in the text pointing to a specific reference in the list. For example.

**Section1**
See this [1], and that [2]
**Section2**
Or maybe this[3]

References
[1] http://
[2] http://
[3] http://

**Comment by jnfoster** [comment]
Then http://madoko.org/reference.html#sec-bib?

**Comment by antoninbas** [comment]
Yes that's what I was suggesting by "abusing the bibliography support". I haven't had time to try it though.

**Comment by jnfoster** [comment]
I see :-)

**Comment by antoninbas** [comment]
Actually we should probably look at the source for the Madoko reference documentation and copy it: http://madoko.org/reference.html#sec-references
