### ISSUE TITLE
Inconsistency in P4Runtime spec regarding consistency guarantees

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4runtime#258]
Section 13.4 (Parallelism of Read and Write Requests) includes the following:
> The processing of any two WriteRequest messages W1 and W2 must result in the same state as if one of them was completed before the other began.

The more recently-updated section 12.1 (Batching and Ordering of Updates) states the following:

The P4Runtime server may choose to reorder updates in a batch when processing them, and/or process updates in parallel. Updates across multiple concurrent WriteRequests can also be processed interleaved and/or in parallel. However, the processing of updates must be strictly serializable. That is, given a history `S` of WriteRequests including the responses to those requests, there must exist an order `L` for all updates in `S`, such that:
1. For two updates `u_1` and `u_2`, if the write request containing `u_1` completed before the write request of `u_2` was sent, then `u_1` must appear before `u_2` in `L`.
2. Executing all updates in `L` sequentially must yield the same response for every update as in `S`.
3. The observable state of the switch after `S` (e.g., through the Read RPC) is identical to the one obtained by sequentially executing `L`.

It seems that the 2 sections are a bit in contradiction. Consider a data plane with a TCAM table `T`, which is at capacity (cannot hold an additional entry). Consider also 2 WriteRequests `W1` and `W2` such that:
* `W1` deletes 2 exiting entries from table `T`: `E1` and `E2`
* `W2` inserts 2 new entries into table `T`: `E3` and `E4`.

If there is no strong ordering of both WriteRequests (i.e. they are sent by the client in parallel and bullet point 1. above does not apply), then it seems that section 12.1 states that the server is allowed to process all 4 updates in the following order: `delete(E1)`, `insert(E3)`, `insert(E4)`, `delete(E2)`, while section 13.4 prevents that kind of interleaving.

State of table `T` after both WriteRequests have been processed:
a. `W1` then `W2`: `T` is at capacity, and contains `E3` and `E4`
b. `W2` then `W1`: `T` has room for 2 new entries, and contains neither `E3` not `E4`
c. `delete(E1)`, `insert(E3)`, `insert(E4)`, `delete(E2)`: `T` has room for 1 new entry, and it contains `E3` but not `E4`.

Only a. and b. are acceptable under 13.4. All orders are acceptable according to 12.1.

**Comment by jnfoster** [comment]
I agree with your diagnosis. Seems like one could either weaken 13.4 or impose additional constraints in 12.1 depending on whether allowing c. is seen as a good thing...
