### ISSUE TITLE
Support action parameter values of `type` types in P4Runtime

### ISSUE THREAD

**Issue by konne-google** [p4lang/p4runtime#263]
Currently, P4RT only supports bits, booleans, newtype, and serializable enums ([source](https://github.com/p4lang/p4c/blob/master/control-plane/p4RuntimeSerializer.cpp#L898)). We should also support parameters of `type` types.

**Comment by antoninbas** [comment]
P4Runtime currently supports user-defined types for match fields, action parameters and controller metadata (for packet IO); see for example https://github.com/p4lang/p4runtime/blob/master/proto/p4/config/v1/p4info.proto#L232.

Looking at the compiler code you are pointing to, it seems that the compiler already supports this case as well:
```
            if (!paramType->is<IR::Type_Bits>() && !paramType->is<IR::Type_Boolean>()
                && !paramType->is<IR::Type_Newtype>() &&
                !paramType->is<IR::Type_SerEnum>()) {
                ::error("Action parameter %1% has a type which is not "
                        "bit<>, int<>, bool, type or serializable enum", actionParam);
                continue;
            }
            int w = getTypeWidth(paramType, typeMap);
            if (w < 0)
                return;
            param->set_bitwidth(w);
            cstring type_name = getTypeName(paramType, typeMap);
            if (type_name) {
                auto namedType = param->mutable_type_name();
                namedType->set_name(type_name);
            }
```
Notice the `!paramType->is<IR::Type_Newtype>()` in the if clause, as well as the end of the code snippet, which takes care of setting the appropriate P4Info field.

Did you try generating the P4Info for a P4 program using a user-defined type as an action parameter? Did it not work? If not, it seems that it should be a compiler issue, not a P4Runtime issue.

**Comment by konne-google** [comment]
Oh, you are actually right, this should already work as expected. I just used an old version of the compiler and didn't parse the code correctly. `IR::Type_Newtype` corresponds to the `type` keyword ([source](https://github.com/p4lang/p4c/blob/master/frontends/parsers/p4/p4parser.ypp#L1053)).

**Comment by jafingerhut** [comment]
A bit of history: For a little while before the `type` keyword was added to P4_16, there were proposals and sample code that used the keyword `newtype`, and the internal compiler implementation was done before the keyword was changed to `type`, IIRC.
