### ISSUE TITLE
Support a string "cookie" in TableEntry

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4runtime#267]
The current "controller_metadata" has type uint64: https://github.com/p4lang/p4runtime/blob/v1.1.0/proto/p4/v1/p4runtime.proto#L160. This is probably legacy from OpenFlow, where each flow can have a 64-bit integer cookie. We would like to be able to store an arbitrary string as metadata with each table entry.

**Comment by antoninbas** [comment]
The decision at the 02/26/2020 P4 API WG was to add a new "metadata" field to the `TableEntry` message, with type string. The old "controller_metadata" field will not be removed to preserve backward-compatibility but will be marked as deprecated. All the use cases covered with a uint64 cookie should be covered with a string cookie. If someone has a better name in mind than just "metadata", please make a suggestion.

**Comment by antoninbas** [comment]
@konne-google should the exact Protobuf type for this type be `bytes` (arbitrary characters) or `string` (only UTF-8 characters)?

**Comment by stefanheule** [comment]
It should be bytes, so arbitrary data can be stored there easily (including the 64bit cookie from before, if someone just needs that after we remove the now deprecated field).

**Comment by stefanheule** [comment]
The ForwardingPipelineConfig message has a 64bit cookie field, too. Do we want to deprecate that in favor of a bytes metadata field as well? Or only for TableEntries? @konne-google @antoninbas, and anyone else who has an opinion?

**Comment by stefanheule** [comment]
Pull request #271 addresses the TableEntry case for now.

**Comment by konne-google** [comment]
I don't feel strongly about the `ForwardingPipelineConfig` either way. We don't need it, but it might be nice for consistency.
