### ISSUE TITLE
P4Info ID generation

### ISSUE THREAD

**Issue by stefanheule** [p4lang/p4runtime#268]
There appears to be confusion between the P4RT spec and the compiler (and me?) when it comes to how IDs are allocated. My understanding from reading the spec is that all IDs are 32 bits, the top most 8 bits are indicating the object type, and the rest is either generated by the compiler or set by using @id.  Specifically, the spec says "It is possible to statically set the least-significant 24 bits of the ID in the P4 program source by annotating the object with @id".

If I take this program and run it through p4c, I get the following P4Info.

```
action a(@id(100) bit<32> arg) {
}

control MyIngress(inout headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
  table t1 {
    key = {
      meta.f1 : exact;
      meta.f2 : exact @id(100); // this is ignored
    }
    actions = {
      a;
      NoAction();
    }
    default_action = NoAction();
  }
  @id(100) // ID does not have the right first 8 prefix bits
  table t2 {
    key = {
      meta.f1 : exact;
    }
    actions = {
      NoAction();
    }
    default_action = NoAction();
  }
  apply {
    t1.apply();
    t2.apply();
  }
}
```

```
pkg_info {
  arch: "v1model"
}
tables {
  preamble {
    id: 33584214
    name: "MyIngress.t1"
    alias: "t1"
  }
  match_fields {
    id: 1
    name: "meta.f1"
    bitwidth: 4
    match_type: EXACT
  }
  match_fields {
    id: 2
    name: "meta.f2"
    bitwidth: 4
    match_type: EXACT
  }
  action_refs {
    id: 16815170
  }
  action_refs {
    id: 16800567
  }
  size: 1024
}
tables {
  preamble {
    id: 100
    name: "MyIngress.t2"
    alias: "t2"
  }
  match_fields {
    id: 1
    name: "meta.f1"
    bitwidth: 4
    match_type: EXACT
  }
  action_refs {
    id: 16800567
  }
  size: 1024
}
actions {
  preamble {
    id: 16815170
    name: "a"
    alias: "a"
  }
  params {
    id: 1
    name: "arg"
    bitwidth: 32
  }
}
actions {
  preamble {
    id: 16800567
    name: "NoAction"
    alias: "NoAction"
  }
}
```

Some observations/questions:
1. The compiler does not set the upper 8 bits correctly, even though I think the spec says it should. Can we clarify what the compiler should do? I think it should add the top 8 bits correctly, and reject IDs that use the upper 8 bits.  Alternatively we could require the user to add the bits manually, and have the compiler reject non-compliant IDs.  I think that is less desirable, but in either case this seems like a compile bug.
2. The compiler completely ignores the ID annotation on match fields, which seems somewhat consistent with the spec. The spec says: "No rules are prescribed on the way MatchField IDs should be allocated, as long as two MatchField of the same table do not have the same ID.". This seems bad, it is likely desirable to be able to chose the ID for match fields and fix them. Would it make sense to use the @id annotation for this?  The same is true for action parameters.

----

The full program is actually this, I abbreviated above for readability:

```
#include <core.p4>

#include <v1model.p4>

struct metadata {
  bit<4> f1;
  bit<4> f2;
}
struct headers {
}


action a(@id(100) bit<32> arg) {
}

control MyIngress(inout headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
  table t1 {
    key = {
      meta.f1 : exact;
      meta.f2 : exact @id(100); // this is ignored
    }
    actions = {
      a;
      NoAction();
    }
    default_action = NoAction();
  }
  @id(100) // ID does not have the right first 8 prefix bits
  table t2 {
    key = {
      meta.f1 : exact;
    }
    actions = {
      NoAction();
    }
    default_action = NoAction();
  }
  apply {
    t1.apply();
    t2.apply();
  }
}



parser MyParser(packet_in packet, out headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
  state start {
    transition accept;
  }
}
control MyVerifyChecksum(inout headers hdr, inout metadata meta) {
  apply {}
}

control MyEgress(inout headers hdr, inout metadata meta, inout standard_metadata_t tandard_metadata) {
  apply {}
}
control MyComputeChecksum(inout headers hdr, inout metadata meta) {
  apply {}
}
control MyDeparser(packet_out packet, in headers hdr) {
  apply {}
}
V1Switch(
  MyParser(),
  MyVerifyChecksum(),
  MyIngress(),
  MyEgress(),
  MyComputeChecksum(),
  MyDeparser()
) main;
```

**Comment by jafingerhut** [comment]
Which ids do you believe have their most significant 8 bits set incorrectly?  At least the tables and actions appear to be correct.  There is no most significant 8 bits value defined by the P4Runtime specification for action parameters or table key fields that I see.

**Comment by stefanheule** [comment]
Okay, I can open a bug for 1. Do we agree that the compiler should set the top 8 bits, and complain if the top 8 bits are set in the annotation but don't match the 8 bit object type tag? Or should the compiler not allow specifying the upper 8 bits at all in the id@ annotation?

For 2, do others agree that it should be possible to use the id@ annotation for field matches and action params?

**Comment by chrispsommers** [comment]
@stefanheule My opinion:
1 - I can think of uses-cases where someone copies some IDs from prior run into the @id annotation to lock them in, and the upper buts are valid, so it would be a pain if the compiler complained. Also it might be convenient to see the ids literally declared in the annottion for referencec. On the other hand, if the upper 8 bits in an @id are non-zero and wrong, they should be rejected. Leaving upper 8 bits = 0 in an @id should be OK.
2 - I don't see harm in allowing @id for match and action params, we should probably stipulate the upper 8 bits = 0 for consistency.

**Comment by jafingerhut** [comment]
It seems like a good idea to me for the compiler to at least warn, if not perhaps an error, if an explicit `@id` annotation for a table, action, etc. tries to use a numeric value 2^24 or larger.  I would recommend creating a separate tiny little test program just for that, which you do not expect to create a P4Info file at all.

I do not know why, but it appears that p4c currently does a bitwise AND of all id values with 0xffff, keeping only the least significant 16 bits, not all least significant 24.  See this line of code, which according to 'git blame' was written by Seth Fowler in Jan 2019: https://github.com/p4lang/p4c/blob/master/control-plane/p4RuntimeSerializer.cpp#L473

I would recommend writing a separate test program that uses `@id` annotations to assign values in the range [2^23, 2^24-1] (so bit 23 is 1) to every kind of P4 object that you care about, and preferable all of them that have an 8-bit type code in the P4Runtime specification, and hand-check the P4Info file to see if they all have the correct most significant 8 bits.

**Comment by jafingerhut** [comment]
I posted my previous comment before reading Chris's previous comment.  Explicitly allowing a user to given an `@id` annotation where the most significant 8 bits had the expected P4Runtime value in bit positions [31:24] seems like a good thing _not_ to warn or error about, and including examples of those in a "working" test case, with hand checking of the expected result file when it is added to the PR, would be good.

**Comment by stefanheule** [comment]
All of this sounds reasonable to me.  AIs are:
1. File a bug in p4c to fix the id behavior for p4 objects: generate upper 8 bits if not present, and check if correct otherwise (and error if incorrect, and allow if correct).
2. Pull requests here to update spec to allow @id annotation to specify id of match fields and action params, and say that the ID is used as it appears in the annotation (no upper 8 bits set automatically).
3. File a feature request against p4c to implement 2.

**Comment by stefanheule** [comment]
All issues have been filed (https://github.com/p4lang/p4c/issues/2241 and https://github.com/p4lang/p4c/issues/2242), and I created a PR to update the spec (#272). I included packetio metadata as a natural extension from just table keys and action params.

**Comment by antoninbas** [comment]
I think this issue has been completely resolved, including with respect to the implementation.
