### ISSUE TITLE
Would "P4runtime id value notes" section be appropriate to add to spec?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#275]
**This is to suggest improvements to the `P4Runtime` specification. For issues regarding a specific implementation, please open an issue with the appropriate repository (e.g. https://github.com/p4lang/behavioral-model or https://github.com/p4lang/PI for bmv2).**

Given the recent addition of ids chosen at P4 compile time (either by the compiler, or by @id annotations) for action parameters, table keys, and controller header fields, and that these are allowed to reuse id values with each other, or those used by the 'top level ids', it seems perhaps useful to collect in one place in the document notes about these scopes, and which id values are determined at P4 program compile time, which are determined by the P4Runtime client, which by the server, and which are currently out of scope of the spec for how they are chosen.

I can create a proposed PR for this if it is of interest -- I may create one even if it isn't of interest to others, as I have started doing so out of my own curiosity. :-). I know such a new section would contain information that was a repeat of information that appears elsewhere in the spec, so may create a little more work/remembering for future maintenance and additions, but seems useful to me.

**Comment by antoninbas** [comment]
It's not really recent and AFAIK all ids are determined at compile time (or in broader terms, at P4Info generation time). Unless you have a very broad definition here that includes things like the election id, multicast group ids, etc.

We already have a fairly long specification document, so I am not too excited about having duplicate information in the spec. However, if you want to add information which is missing to the spec, or if you want to write a companion document like you did with https://github.com/p4lang/p4runtime/blob/master/docs/v1/guidance-for-generating-p4info.md, that sounds good to me.

**Comment by jafingerhut** [comment]
I am thinking more broadly about ids, including the examples you mention.  Several seem to fit into the category of "chosen at run time by client and/or server", and some seem to have a selection mechanism that the P4Runtime spec doesn't try to nail down, e.g. role ids.

A companion document seems reasonable to me, and I can create a PR that does that.

**Comment by jafingerhut** [comment]
I created this PR, with a single new added Github-flavored Markdown file added, in a completely separate file from, and not directly affecting or incorporated into the P4Runtime specification document: https://github.com/p4lang/p4runtime/pull/281

**Comment by antoninbas** [comment]
Closing this now that we have merged https://github.com/p4lang/p4runtime/pull/281
