### ISSUE TITLE
Should DigestList messages somehow identify the device that created the digest messages?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#277]
I do not see any way for a P4Runtime client to identify which of several devices within a single server that digest messages were generated by.  Is there a way?  If not, should there be?  Two possible options for adding this would be:

(a) restrict all digest messages inside of a `DigestList` message to come from the same device.  This would allow adding a single device_id field to a `DigestList` message that would apply to all of the perhaps many `data` field values it contains, one per digest message generated by a device.

(b) Allow a single `DigestList` message to contain a mix of digest messages from multiple devices.  This would require some way to identify which ones come from which device.

**Comment by jafingerhut** [comment]
A similar question applies for `IdleTimeoutNotification` messages.  I see no way for a client to determine which device_id the notifications are for.  If a `device_id` field should be added somehow, a similar design alternative exists as mentioned above, i.e.

(a) restrict all notifications in a single `IdleTimeoutNotification` to come from the same device, and thus add a single `device_id` field to that message.

(b) allow a single `IdleTimeoutNotification` to contain notifications from multiple devices, and then a new message type seems to be required to specify an independent `device_id` with each `TableEntry` in the notification.

**Comment by jafingerhut** [comment]
It appears that DigestList, DigestListAck, IdleTimeoutNotification, PacketIn, and PacketOut might be a complete list of messages that lack a way of specifying the device_id, from my review of all messages possible in a StreamMessageRequest or StreamMessageResponse.  The other possible messages there already have a device_id, as do WriteRequest and ReadRequest.

**Comment by antoninbas** [comment]
Each `StreamChannel` bi-directional is associated with a single device id. When a client opens the stream with the intention of becoming a controller for a given device, it sends a `MasterArbitrationUpdate` with the appropriate device id + role id + election id. If it is selected by the server as master for that device (& role), the client will start receiving "notification" messages (idle timeout notifications, digest lists, packet-ins) for that device, and that device only.

From the P4Runtime spec:

> Note that the stream is opened per device. In case a switching platform has multiple devices (e.g. multi-ASIC line card) which are all controlled via the same P4Runtime server, it is possible to have different masters for different devices. In this case, it is the responsibility of the P4Runtime server to keep track of the master for each device (and role). More specifically, the P4Runtime server will know which stream corresponds to the master controller for each pair of (device_id, role_id) at any point of time.

**Comment by jafingerhut** [comment]
Thanks.  Sorry for the noise.  Makes sense.  I guess the odd part is that MasterArbitrationUpdate messages include a device_id, and are sent over the StreamChannel?

**Comment by antoninbas** [comment]
Yes, `MasterArbitrationUpdate` includes the device id and that's how the client "binds" a `StreamChannel` to a specific device. We use the same message (`MasterArbitrationUpdate`) for the other direction (server -> client) for mastership status updates, but I believe that was mostly for convenience and to avoid having to define another message. While device id is included for that direction as well, it is not really required in theory. A bit like how the `status` field in that message is never set in the client -> server direction.

> Note that the status field in the MasterArbitrationUpdate message is not populated by the controller. This field is populated by the P4Runtime server when it sends a StreamMessageResponse message back to the controller, in which it populates the MasterArbitrationUpdate message using the device_id, role, and election_id it previously received from the controller. The server also populates the status field in the MasterArbitrationUpdate according to the rules in an earlier section.
