### ISSUE TITLE
Should there be defined behavior for using action selector group with all members unusable due to watched ports being down?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#280]
If the behavior is already specified somewhere, happy to be pointed at it and review it.

If it is not already specified, I am not sure what existing targets might do in this situation already, but seems it might be a good idea to document what they do today.

**Comment by jafingerhut** [comment]
In the context of the PSA specification, where there is an optional table property `psa_empty_group_action`, it seems reasonable to say that a group where all members have currently-down watch ports should be treated like an empty group.

Since I am unaware of any current PSA implementation, that does not necessarily say anything at all about what existing implementations of the P4Runtime API actually do in this case.

**Comment by antoninbas** [comment]
There is a section on empty groups (https://p4.org/p4runtime/spec/v1.1.0/P4Runtime-Spec.html#sec-constraints-on-action-selector-programming), but it does not make the connection with groups which become empty because all the watch ports are down. I think that could be a valuable addition.

**Comment by jafingerhut** [comment]
Is it already documented somewhere that a `watch` value of 0 means "never disable this action selector group member based upon port up/down status"?  Is that the intended behavior?

Should it be an error if one attempts to add a member with a `watch` value that is anything other than (a) a valid SDN port number, or (b) 0?

**Comment by jafingerhut** [comment]
This PR is a first draft of possible changes to answer the questions above.  I may be going out on a limb on the answers, so please correct or suggest improvements if the changes look undesirable for any reason: https://github.com/p4lang/p4runtime/pull/282

**Comment by jafingerhut** [comment]
Closing as completed, since this PR addressing the questions in this issue has been merged: https://github.com/p4lang/p4runtime/pull/282
