### ISSUE TITLE
`bitwidth` field for "translated" action params / match fields with "string" controller type

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4runtime#293]
This is the test P4 program added by @smolkaj to p4lang/p4c when he added support for "string" translation (https://github.com/p4lang/p4c/pull/2365):
```
#include <core.p4>
#include <v1model.p4>

typedef bit<16> PortIdUint_t;

// Legacy syntax.
@p4runtime_translation("p4.org/psa/v1/PortId1_t", 32)
type PortIdUint_t PortId1_t;

// New syntax.
@p4runtime_translation("p4.org/psa/v1/PortId2_t", bit<32>)
type PortIdUint_t PortId2_t;

// New syntax.
@p4runtime_translation("p4.org/psa/v1/PortId3_t", string)
type PortIdUint_t PortId3_t;

header ports_t {
    PortId1_t port1;
    PortId2_t port2;
    PortId3_t port3;
}

struct Headers {
    ports_t ports;
}

struct Meta {}

parser p(packet_in pkt, out Headers hdr, inout Meta m, inout standard_metadata_t sm) {
    state start {
        pkt.extract(hdr.ports);
        transition accept;
    }
}

control vrfy(inout Headers h, inout Meta m) { apply {} }

control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    table t {
        key = {
            h.ports.port1 : exact;
            h.ports.port2 : exact;
            h.ports.port3 : exact;
        }
        actions = {
            NoAction;
        }
    }
    apply { t.apply(); }
}

control egress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    apply {}
}

control update(inout Headers h, inout Meta m) { apply {} }

control deparser(packet_out b, in Headers h) { apply {b.emit(h);} }

V1Switch(p(), vrfy(), ingress(), egress(), update(), deparser()) main;
```
It yields this P4Info message:
```
pkg_info {
  arch: "v1model"
}
tables {
  preamble {
    id: 34728461
    name: "ingress.t"
    alias: "t"
  }
  match_fields {
    id: 1
    name: "h.ports.port1"
    bitwidth: 32
    match_type: EXACT
    type_name {
      name: "PortId1_t"
    }
  }
  match_fields {
    id: 2
    name: "h.ports.port2"
    bitwidth: 32
    match_type: EXACT
    type_name {
      name: "PortId2_t"
    }
  }
  match_fields {
    id: 3
    name: "h.ports.port3"
    bitwidth: 16
    match_type: EXACT
    type_name {
      name: "PortId3_t"
    }
  }
  action_refs {
    id: 21257015
  }
  size: 1024
}
actions {
  preamble {
    id: 21257015
    name: "NoAction"
    alias: "NoAction"
    annotations: "@noWarn(\"unused\")"
  }
}
type_info {
  new_types {
    key: "PortId1_t"
    value {
      translated_type {
        uri: "p4.org/psa/v1/PortId1_t"
        sdn_bitwidth: 32
      }
    }
  }
  new_types {
    key: "PortId2_t"
    value {
      translated_type {
        uri: "p4.org/psa/v1/PortId2_t"
        sdn_bitwidth: 32
      }
    }
  }
  new_types {
    key: "PortId3_t"
    value {
      translated_type {
        uri: "p4.org/psa/v1/PortId3_t"
        sdn_string {
        }
      }
    }
  }
}
```
Notice how the `bitwidth` field for the match field with type `PortId3_t` is 16, while it is 32 for the others. I find it confusing that when the controller type is `string` we set `bitwidth` to the width of the underlying type, while when the controller type is `bit<W>`, `bitwidth` is set to `W`.

It may be a good idea to "set" `bitwidth` to 0 for `string` controller types. For uniformity, it may not be such a bad idea to also use 0 when the controller type is `bit<W>`, since using the `type_name` information, one can access the SDN bitwidth. But maybe that's a bit of a disruptive change.

Note that https://github.com/p4lang/p4runtime/pull/274 did not specify how to handle that `bitwidth` field, so whatever is described above is just the current behavior of the p4c compiler. We should update the spec to clarify this case, and including a concrete example in https://p4.org/p4runtime/spec/v1.1.0/P4Runtime-Spec.html#sec-translation-of-match-fields may be a good idea.

**Comment by stefanheule** [comment]
Thank Antonin, this is a really good catch!

Could it make sense to actually always set it to the underlying HW bitwidth? It seems like that would strictly be more information, even though I agree that the controller in almost all cases will not look at that, and instead look at the named type.

**Comment by smolkaj** [comment]
Using the underlying HW bitwidths in `match_field { ... }` seems intuitive to me; this makes the `table { ... }` message a description of the hardware pipeline rather than the "logical pipeline", which seems in line with the current spirit of that message.

**Comment by antoninbas** [comment]
At the 06/03/2020 P4 API WG meeting (https://docs.google.com/document/d/1qzeAnKDDOIgBzq3sLS1C1CacunTtrV5x5T5xPXUFRGM/edit#heading=h.o7ihlyha8cwb), we decided to use a bitwidth of 0 (which is the default value for an int32 field in Protobuf3) for match fields (& action params, etc.) with "string" translation.
