### ISSUE TITLE
What is the default / recommended TCP port to run a P4Runtime server on?

### ISSUE THREAD

**Issue by pudelkoM** [p4lang/p4runtime#306]
I could not find a reference to that in the spec.
Is it even desirable to define a standard port?

For reference: [IANA](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=9339) lists TCP port 9339 for gNMI.

**Comment by bocon13** [comment]
OpenFlow is 6653 (or 6633 originally)

Combining that with gNMI to make it easy to remember, I get **9559** (available)

If you need an org for the registration:
Open Networking Foundation <iana@opennetworking.org>

**Comment by antoninbas** [comment]
Thanks for the pointers @bocon13. I have submitted the application on behalf of the ONF and it is under review. Will update this issue when I hear back from them.

**Comment by antoninbas** [comment]
It's my pleasure to announce that IANA has approved our request to assign port 9559 for P4Runtime: https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=p4runtime.

The next step - before we can close this issue - would be for us to update the P4Runtime specification to reference this port number.

**Comment by chrispsommers** [comment]
Very nice!
