### ISSUE TITLE
Spec uploads to S3

### ISSUE THREAD

**Issue by bocon13** [p4lang/p4runtime#339]
It appears that the spec is being uploaded to S3 in addition to GH Pages:

Upload to S3
https://github.com/p4lang/p4runtime/blob/a1529acd1532eb084f6aad19b47a856043c1eb5c/.travis.yml#L36-L48

Upload to gh-pages
https://github.com/p4lang/p4runtime/blob/a1529acd1532eb084f6aad19b47a856043c1eb5c/.travis.yml#L68-L73

Should we move the S3 one? Where is that being used?

**Comment by antoninbas** [comment]
It's only used to do test builds and rendering of the spec, so I wouldn't worry about the S3 ones
see https://github.com/p4lang/p4runtime/tree/main/docs#ci-upload-of-built-documents

**Comment by bocon13** [comment]
Got it. Thanks!
