### ISSUE TITLE
Fix broken spec link

### ISSUE THREAD

**Issue by debnil** [p4lang/p4runtime#350]
The [link](https://p4.org/p4runtime/spec/main/P4Runtime-Spec.html) to the P4Runtime spec is broken - it just goes to the blog. All other specifications have the same problem.

Let me know if there's a better place to file this issue. Thanks!

**Comment by alpinesnow** [comment]
We just launched the new website today and are still ironing out some issues. In the meantime, you can visit https://p4.org/specs to get the links. They point directly to github, https://p4lang.github.io/p4runtime/spec/v1.3.0/P4Runtime-Spec.html, until we fix the p2.org link, https://p2.org/p4runtime/spec/v1.3.0/P4Runtime-Spec.html.
Sorry for the inconvenience!

**Comment by antoninbas** [comment]
Links were updated (temporarily?) with https://github.com/p4lang/p4runtime/pull/353
