### ISSUE TITLE
Clarify wording around "no-op" master arbitration updates

### ISSUE THREAD

**Issue by smolkaj** [p4lang/p4runtime#361]
Section 5.3.2.(e).ii of the spec, see attachment, states:

> If the controller is a backup, this is a no-op and the role.config is ignored. No response is sent to any controller.

This seems to suggest that in this case, we shouldn't even send a reponse to the controller originating the `MasterArbitrationUpdate`.

Is this phrasing intended? If so, what is the motivation?

Sending an ALREADY_EXISTS response to the controller originating the `MasterArbitrationUpdate` would be more consistent with the rest of the spec (in particular, section 5.4), eliminating this special case. 

![spec](https://user-images.githubusercontent.com/6642034/126395901-8a4736e2-e79f-40ca-bddf-36c981379614.png)

**Comment by smolkaj** [comment]
@antoninbas @jonathan-dilorenzo @rhalstea for visibility

**Comment by jonathan-dilorenzo** [comment]
If I am correctly understanding your suggestion, you want to remove all of 5.3.2.(e) since the information touched on is covered just below, except that this induces a spec change where 5.3.2.(e).ii is no longer a no-op. 

This makes sense to me!

**Comment by smolkaj** [comment]
Thanks for clarifying. Indeed this is the intention. Though I think we still need to keep 5.3.2.(e) to say how to update `role.config`.

**Comment by jonathan-dilorenzo** [comment]
I think we shouldn't need that because it seems to be covered by the first point of "If the MasterArbitrationUpdate is accepted":

"If election_id is greater than or equal to election_id_past, then the controller becomes primary. The server updates the role configuration to role.config for the given role.id."

**Comment by smolkaj** [comment]
Good point. We may still have to say when the MasterArbitrationUpdate is accpeted in 5.3.2.(e) then, I believe. Maybe we can merge (e) and (f).
