### ISSUE TITLE
Can an arbitration triple be reused after the StreamChannel associated with it is closed? 

### ISSUE THREAD

**Issue by smolkaj** [p4lang/p4runtime#365]
The specification currently says:

> The P4Runtime server only keeps track of the (device_id, role, election_id) of each StreamChannel that has sent a successful MasterArbitrationUpdate message, and maintains the invariant that all such 3-tuples are unique. 

But how is the set X of 3-tuples determined?
It is clear that we add a tuple to X whenever a master arbitration succeeds.
Do we also remove tuples from X when the controller owning the tuple disconnects?

@jonathan-dilorenzo @zhenk14 for visibility.

**Comment by smolkaj** [comment]
AFAICT, the more sensible thing to do is to remove tuples when a controller disconnects, so we can gracefully reconnect without a new election ID.

Are there any advantages to *not* allowing reuse of the same tuple in the above fashion?

**Comment by smolkaj** [comment]
@rhalstea pointed out the following related ambiguity in the spec:
![image](https://user-images.githubusercontent.com/6642034/142661361-e93a4423-67f0-4a5e-aeb1-5c84650ed962.png)

**Comment by smolkaj** [comment]
Quick recap of our discussion during the P4 API WG meeting:

* Use cases for reusing an election ID:
  1. The connection between the primary controller and switch has an intermittent flake and brakes, and the primary controller attempts to quickly reconnect. If this succeeds within a short time, there is no need to elect a new primary, which requires running a more costly distributed systems leader election.
  2. The controller maintains multiple connections to the switch, i.e. one in band and one out-of-band. All but one connection connect without election IDs, making them standby connections; one connection uses an election ID and becomes the primary connection. If the primary connection then fails, the controller can quickly upgrade a standby connection to primary by sending another arbitration update with the existing election ID. Again, we avoid kicking off a more costly leader re-election.

* There were no concrete concerns around reusing the maximum election ID, as long as we keep ensuring uniqueness.

The next step here is for us to make a concrete proposal on how to clarify the spec.

**Comment by antoninbas** [comment]
Should we close this issue now?

**Comment by jonathan-dilorenzo** [comment]
Yes. The merged PR should resolve this.
