### ISSUE TITLE
Documentation does not seem to update for each main branch push.

### ISSUE THREAD

**Issue by jonathan-dilorenzo** [p4lang/p4runtime#367]
In the main readme, it says: "[The documentation] is updated every time a new commit is pushed to the main branch."

I just noticed that this does not seem to be happening automatically since the last documentation update was in early July.

**Comment by antoninbas** [comment]
Thanks for reporting this @jonathan-dilorenzo. I will look into this. Unfortunately it seems that the source for the p4.org website is no longer hosted in this Github organization, as the https://github.com/p4lang/p4lang.github.io repo is tagged as deprecated.

**Comment by jfingerh** [comment]
Antonin and I have been discussing this in the past week or so.  I am in contact with a maintainer of the P4.org web site at ONF that might be able to help update the "working draft" links so they actually point at the latest auto-generated versions, instead of whatever they point at now.  Stay tuned.

**Comment by smolkaj** [comment]
Thanks for looking into this. This seems like a really important issue to fix.

**Comment by jafingerhut** [comment]
OK, we are getting close.  Here is a personal test web page that has the current links to the latest released versions from the https://p4.org/specs/ page, and copies of the currently wrong/bad "working draft" links, plus "proposed new links" that are working, thanks to the efforts of Antonin Bas, Nate Foster, and myself: https://jafingerhut.github.io/p4-specs/p4-specification-documents.html

Please do not pass this page around, as it might be deleted soon, but we do hope to get these "proposed new links" installed in the appropriate places on the p4.org/specs page soon.

Yay!  Progress!

**Comment by jnfoster** [comment]
"Always bet on JS" :-)

**Comment by jnfoster** [comment]
Minor, but I'd suggest updating with the final versions that I sent to Denise. They are pure JS and don't even use JQuery. Being leaner and meaner, they should be less prone to bit-rot.

HTML
```html
<!DOCTYPE html>
<html>
<head>
<script>
const url = "https://raw.githubusercontent.com/p4lang/p4-spec/gh-pages/docs/P4-16-working-spec.html";  
const req = new XMLHttpRequest();
req.open("GET", url, true);
req.onload = (_) => {
    const doc = document.open("text/html", "replace");
    doc.write( req.response );
    doc.close();
};
req.send(null)
</script>
</head>
<body></body>
</html>
```

PDF
```html
<!DOCTYPE html>
<html>
<head>
<script>
const url = "https://raw.githubusercontent.com/p4lang/p4-spec/gh-pages/docs/P4-16-working-spec.pdf";
const req = new XMLHttpRequest();
req.open("GET", url, true);
req.responseType = "arraybuffer";
req.onload = (_) => {
  const blob = new Blob([new Uint8Array(req.response)], { type: "application/pdf" });
  var newUrl = URL.createObjectURL(blob);
  window.location.href = newUrl;
};
req.send(null);
</script>
</head>
<body>
</body>
</html>
```

**Comment by smolkaj** [comment]
Looks like JS code written by an OCaml hax0r ;) Beautiful!

**Comment by jafingerhut** [comment]
Thanks for noticing, Nate.  I got your latest email with those versions, but somehow copied the one that was one version older.  Updated now.

**Comment by jafingerhut** [comment]
The links on this page are now good: https://p4.org/specs/

This PR should, I believe, make the working draft links in this repo's README also point at the same places: https://github.com/p4lang/p4runtime/pull/402

**Comment by jonathan-dilorenzo** [comment]
Amazing, thanks so much for fixing this!
