### ISSUE TITLE
API for GetForwardingpipelineconfig

### ISSUE THREAD

**Issue by Johnny-dai-git** [p4lang/p4runtime#397]
HI, 

I am trying to use the GetForwardingpipelineconfig RPC to retrieve the p4info from the device ( simple_switch_grpc with start with input json file).

However, I can not find enough information to help me finish this goal and I do not see the support api in the switch.py.

Could we have such feature and API ? It will provide greate help in some scenario.

Best Regards,

**Comment by antoninbas** [comment]
> I am trying to use the GetForwardingpipelineconfig RPC to retrieve the p4info from the device ( simple_switch_grpc with start with input json file).

`GetForwardingPipelineConfig` cannot retrieve a P4Info if you didn't previously push it to the switch with `SetForwardingPipelineConfig`. Providing a json file to `simple_switch_grpc` when starting the process is _not_ the recommended way to use `simple_switch_grpc` with P4Runtime, as mentioned in the [documentation](https://github.com/p4lang/behavioral-model/tree/main/targets/simple_switch_grpc).

> However, I can not find enough information to help me finish this goal and I do not see the support api in the switch.py.

I don't know what switch.py refers to. But hopefully the P4Runtime spec describes usage of `SetForwardingPipelineConfig` / `GetForwardingPipelineConfig` with enough details.

> Could we have such feature and API ? It will provide greate help in some scenario.

If you mean support for `GetForwardingPipelineConfig` without an earlier call to `SetForwardingPipelineConfig`, no that won't be supported. It doesn't make sense in the context of P4Runtime. And bmv2 / `simple_switch_grpc` has no ability to generate the P4Info from the bmv2 JSON.

If you need more examples for using P4Runtime, I can refer you to:
- https://github.com/p4lang/p4runtime-shell [Python]
- https://github.com/antoninbas/p4runtime-go-client [Golang]

Finally, the [P4 forum](https://forum.p4.org/) is a better place to ask such questions. You can also search through previously asked questions.
