### ISSUE TITLE
 Error: P4Runtime RPC error (INTERNAL): 'bf_pal_device_add(dev_id, &device_profile)' failed with error message: Unexpected error.

### ISSUE THREAD

**Issue by guy-davidi** [p4lang/p4runtime#413]
Hi just encountered this issue while trying to load pipline to DPDK after compilation by using the P4RUNTIME.
can you please assist ?

```
Error: P4Runtime RPC error (INTERNAL): 'bf_pal_device_add(dev_id, &device_profile)' failed with error message: Unexpected error.```

**Comment by smolkaj** [comment]
Hi @guy-davidi, this repository defines the P4Runtime protocol, but does not implement the protocol.

Your issue seems to be with DPDK's implementation of the P4Runtime protocol. I suggest filing an issue with the P4 DPDK maintainers.
