### ISSUE TITLE
Clean up or remove "TODO" text in v1/docs

### ISSUE THREAD

**Issue by chrispsommers** [p4lang/p4runtime#434]
This content seems very outdated: https://github.com/p4lang/p4runtime/tree/main/docs/v1#content-todo, namely:
>Following are major content items which are missing or incomplete: 
Section 17. P4Runtime Versioning
Section 18. Extending P4Runtime for non-PSA architectures
Section 19. Lifetime of a session

we could do this as part of a PR for closing https://github.com/p4lang/p4runtime/issues/424

**Comment by jafingerhut** [comment]
@jafingerhut I volunteered to creating a PR for this issue, and to simultaneously address #424 for now by simply stating something like this "Version X.Y.Z of the P4Runtime spec is compatible with version 1.2.4 of the P4_16 Language Specification, except for these known omissions" and then give a bullet list of the approximately 3 items we know we haven't addressed yet..
