### ISSUE TITLE
New protobuf entities should have a comment of the form "Added in x.y.z"

### ISSUE THREAD

**Issue by smolkaj** [p4lang/p4runtime#441]
Context: https://github.com/p4lang/p4runtime/pull/432#discussion_r1212101247

I propose that going forward, when adding new fields/messages/services to our P4Runtime protobuf schemas, we always include comments such as
```
// Added in 1.4.0.
```
This allows developers to reason about forward/backward compatibility of various sever/client combinations when the server and client may be using different versions of the protobuf schemas.

@jafingerhut @chrispsommers WDYT?

**Comment by chrispsommers** [comment]
Seems like a good ideato me!

**Comment by jafingerhut** [comment]
Agreed
