### ISSUE TITLE
What is the expect behavior of wildcard reading CounterEntry with `counter_id = 0` and `index = x`?

### ISSUE THREAD

**Issue by duskmoon314** [p4lang/p4runtime#478]
I'm reading the doc of reading and writing CounterEntry and getting confused about wildcard reading.

In the [doc](https://github.com/p4lang/p4runtime/blob/main/docs/v1/P4Runtime-Spec.mdk#L4260-L4264):
```
* If the `counter_id` field is set to 0 (default), the server returns the
  counter values for all indirect counter instances in the `ReadResponse`.

* If the `index` field is not set, the server returns the counter values for all
  indirect counters in the array identified by the unique id `counter_id`.
```
> Is `for all indirect counters` actually `for all indirect entries`? It seems like a typo.

In the [proto](https://github.com/p4lang/p4runtime/blob/main/proto/p4/v1/p4runtime.proto#L391-L392):
```
// - All counter cells for all counters if counter_id = 0 (default).
// - All counter cells for given counter_id if index is unset (default).
```

To my understanding, the results of different parameters are:
- `counter_id: x, index: y` => one entry of counter `x` and its index is `y`
- `counter_id: x, index: UNSET` => all entries of counter `x`
- `counter_id: 0, index: UNSET` => all entries of all counters
- `counter_id: 0, index: y` => Undefined behavior? Or all entries that index are `y`? Or does some error indicate that the parameter is illegal?

**Comment by antoninbas** [comment]
If the `counter_id` field is set to 0, then I would expect a P4Runtime implementation not to even bother looking at the `index` field, and the value you set should be irrelevant.

Maybe the second bullet point should just start with `Otherwise, `, to make it clear that these 2 checks are really ordered and mutually exclusive.

**Comment by chrispsommers** [comment]
@duskmoon314 Would you like to submit a PR to clarify the spec's language per @antoninbas 's feedback above? It'd be great to get your contribution. Thanks in advance!

**Comment by duskmoon314** [comment]
Sure! I have submitted a PR based on the feedback above.

I'm sorry for responding late due to some personal issue.
