### ISSUE TITLE
Scrub all changes to Protobuf files since last release to verify that they have "Added in 1.4.0" comment for new fields.

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#487]
For example, this PR appears not to have such comments on new fields that it added: https://github.com/p4lang/p4runtime/commit/fee499a02261f7380070e34d9edf4ab5c4ac59e5

It would be good to do something like this and go through every change to the .proto files since the last release to verify whether all new fields are marked as new in 1.4.0, if they are.

```
git clone https://github.com/p4lang/p4runtime
cd p4runtime
git diff v1.3.0 HEAD proto
```

**Comment by chrispsommers** [comment]
Merged into version-1.4.0-rc https://github.com/p4lang/p4runtime/pull/490#
Intended to be merged into main
