### ISSUE TITLE
Fix incorrect statement in spec that device port number 0 is invalid in PSA

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4runtime#49]
I don't believe that PSA has that restriction and I actually found an example in the PSA spec that mentions port 0 as a valid port. While it makes sense that the SDN port 0 be invalid, there is no reason for device port 0 to be invalid. I know of hardware targets for which it is not the case.

**Comment by jafingerhut** [comment]
At least for port ids, that was the original motivating use case for numeric translation between control plane and data plane values in a P4Runtime server, so making it valid in the data plane but invalid in the control plane is straightforward.
