### ISSUE TITLE
Upgrade to Ubuntu 24.04

### ISSUE THREAD

**Issue by smolkaj** [p4lang/p4runtime#514]
GitHub Actions recently upgraded `ubuntu-latest` from `22.04` to `24.04`: https://github.com/actions/runner-images/issues/10636

However, this broke our builds and thus we temporarily pinned to `22.04`: https://github.com/p4lang/p4runtime/pull/513
This issue tracks making our builds compatible with `24.04` and moving back to `ubuntu-latest` as a healthy forcing function to prevent bit rot.

cc @chrispsommers @jafingerhut

**Comment by smolkaj** [comment]
@fruffy @jonathan-dilorenzo have you by any chance dealt with this problem for p4c yet? Any pointers you'd be able to share?

**Comment by fruffy** [comment]
Do not use ubuntu-latest in the actions, instead specify the version explicitly. This should avoid the problem. 

https://github.com/p4lang/p4c/blob/main/.github/workflows/ci-test-debian.yml#L19

**Comment by fruffy** [comment]
Most Ubuntu 24.04 are related to Python breaking changes. They are quite the pain to deal with.

**Comment by smolkaj** [comment]
> Do not use ubuntu-latest in the actions, instead specify the version explicitly. This should avoid the problem.
> 
> https://github.com/p4lang/p4c/blob/main/.github/workflows/ci-test-debian.yml#L19

Yup, that's what we did: https://github.com/p4lang/p4runtime/pull/513

However, I actually think *NOT* pinning versions is a healthy forcing function to prevent bit rot, so I'm hoping to revert to `ubuntu-latest` once we have gotten things to work with Ubuntu 24.04.

**Comment by fruffy** [comment]
> However, I actually think _NOT_ pinning versions is a healthy forcing function to prevent bit rot, so I'm hoping to revert to `ubuntu-latest` once we have gotten things to work with Ubuntu 24.04.

In that case you might break older versions though, which can be disruptive. For example, the compiler guarantees to support Ubuntu 20.04, 22.04, MacOS Ventura and Sonoma. We even still support Ubuntu 18.04. To start supporting newer versions we eventually just add the action explicitly once the build system is ready. To deprecate a version we create an explicit issue, too.
