### ISSUE TITLE
Should the P4Runtime spec include a generic section on atomicity of individual operations?

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4runtime#54]
Similar to the "Atomicity of control plane API operations" section in the PSA spec (https://github.com/p4lang/p4-spec/blob/master/p4-16/psa/PSA.mdk#L2437)?
We can also just add a link to the PSA spec section somewhere...

**Comment by jnfoster** [comment]
As discussed in the PSA repo, to avoid confusion about which semantics is "definitional", I would recommend summarizing what's in the Language Spec and adding a pointer to that document, and then adding any further guarantees that P4 Runtime guarantees.

**Comment by antoninbas** [comment]
@jnfoster I'm not seeing anything about atomicity of control-plane operations in the P4 spec right now.
@jafingerhut was there a plan to move the "Atomicity of control plane API operations" section from the PSA spec to the language spec?

**Comment by jafingerhut** [comment]
The last time I recall this topic coming up for a discussion in a P4 language design WG meeting, the preference seemed to be to include such information in the architecture specifcation(s), not the language spec.  I thought there was an even clearer statement of this in the P4_16 language spec, but looking today this is the most relevant statement I could find:

"16.4.1. Concurrency model
A typical packet processing system needs to execute multiple simultaneous logical “threads.” At the very least there is a thread executing the control plane, which can modify the contents of the tables. Architecture specifications should describe in detail the interactions between the control-plane and the data-plane."

That said, I don't have a problem if someone wants to describe these kinds of requirements in documents other than PSA.

**Comment by antoninbas** [comment]
In this case, I will add a pointer to the PSA spec for this and add a small one paragraph summary.

**Comment by jnfoster** [comment]
Indeed, that's the section I was thinking of. 

@anirudhSK wrote this text.

I'd be happy to refine it or add pointers to other specs as necessary.

-N

**Comment by anirudhSK** [comment]
@mbudiu-vmw and I drafted that together. I don't have the full context for the discussion in this pull request, but I am happy to help out if needed.
