### ISSUE TITLE
Include more information about what a role is

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4runtime#56]
This is based on question I get on p4.org.
In the "Master-Slave Arbitration and Controller Replication" section I suggest adding something like this:

> The definition of a role (out-of-scope) may also include the following:
x Ability to send `PacketOut` messages to the server
x Ability to receive `PacketIn` messages from the server, along with filtering / subscription mechanism based on the value of the `PacketMetadata` fields for each `PacketIn`

As well as

> Each master controller will only receive `DigestList` and `IdleTimeoutNotification` messages if the corresponding P4 object is included in its role.

Thoughts?

**Comment by jnfoster** [comment]
Suggest we find different terminology than "master-slave."
