### ISSUE TITLE
Clarify the meaning of COLOR_AWARE meter in the spec

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4runtime#58]
And in particular in relation with the PSA specification
When is the meter type set to `COLOR_AWARE`?

**Comment by jafingerhut** [comment]
I think the color aware vs. color blind distinction could be completely invisible and unknown to the control plane and API.  The only difference is the call made to update the meter in the P4 program, not in how the meter is configured at run time.  Regardless of whether the P4 program uses it in color aware mode, or color blind mode, the control plane can configure peak and/or committed rates and burst sizes in exactly the same way.

If for some reason a particular P4 program wanted to provide the option for the control plane to choose between the two kinds of updates in the data plane code, it could do so via the usual ways, e.g. provide two different action names for a table that have different behavior in the actions, just like a table could provide one set of actions that update direct counters, and another set of actions that do not update direct counters.

**Comment by antoninbas** [comment]
Sounds good to me. I'll open a PR to remove the color-awareness information. I don't think anyone will have backwards-compatibility concerns for this.
