### ISSUE TITLE
Inconsistent names in proto message fields and clone examples

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#62]
I am not up to speed on the full contents of this repo, so may be out of date, but I was reviewing the parts of the spec related to creating packet clones to multiple ports, and found some names that look inconsistent.

Here is the part of the proto file I'm looking at: https://github.com/p4lang/p4runtime/blob/master/proto/p4/v1/p4runtime.proto#L401-L436

and here is the part of the spec I'm looking at: https://github.com/p4lang/p4runtime/blob/master/docs/v1/P4Runtime-Spec.mdk#L3031-L3043

I would be happy to create a PR for making these consistent, assuming they should be.

Question: Should I assume the names in the proto file are the up to date ones, and update the names used in the spec to match?  Or vice versa?

**Comment by antoninbas** [comment]
Yes please do open a PR if you have time. Let's make the proto files the source of truth for this to avoid breaking code, unless you find something wrong in there. Thanks!

**Comment by jafingerhut** [comment]
PR created: https://github.com/p4lang/p4runtime/pull/63
