### ISSUE TITLE
Does choice of representing serializable enums violate the read-write symmetry principle?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#64]
Section 8.5.5 titled "enum, serializable enum and error" says:

"When providing serializable enum values through P4Data, one can either use the enum entry's name (enum human-readable string field) or its assigned value (enum_value bytestring field)."

That seems to imply one of two things to me:

(1) it breaks read-write symmetry, because if a client chooses to write with the string, but reads back an integer (or vice versa), the messages are not equal

or

(2) read-write symmetry is preserved, because when comparing the read to the write data, one must consider a numeric value and its corresponding string value for a serializable enum to be equal.

or maybe there is a 3rd possibility I'm not thinking of.

**Comment by antoninbas** [comment]
This by itself doesn't violate read-write symmetry unless the server doesn't return the same value as the client. However, it does make read-write symmetry hard and impractical to achieve, so we should probably pick a canonical representation for serializable enum values. Let's discuss it at the next meeting and take a decision then. I personally don't have a strong preference. For the sake of simplicity using the same representation (string) as for safe enums would make sense. For the sake of efficiency, using a binary string may be better.

**Comment by antoninbas** [comment]
That's a good point. I guess that solves the issue of picking one representation over the other :)
We will keep the mapping from name to integer value in the P4Info message, so clients will be able to get the value for named enum members if needed.

**Comment by antoninbas** [comment]
I have opened a PR for this. We should still bring it up at the next WG meeting though.
