### ISSUE TITLE
Should we remove the "alias" field from the P4Info preamble?

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4runtime#97]
With retrospect it is not clear to me what the value of "alias" is. P4_16 enables the programmer to set the name of every entity to an arbitrary value, even when it is nested within an arbitrary number of P4 controls. For example, annotating a table `T1`, nested within control `X` with annotation `@name(".T2")` will rename the table from `X.T1` to `T2`.

If there is some value in providing an additional alias to an entity, I don't see it. And if there is some value, we should define an `@alias` annotation so that the programmer can set this alias.

I do believe that a library which uses P4Info to offer an API for mapping names to ids, may want to accept all unique prefixes for an entity instead of just the exact name. This is actually convenient when writing tests (see https://github.com/opennetworkinglab/fabric-p4test/blob/master/tests/ptf/base_test.py#L229 for example). However, that does not require the alias field at all (the comment in P4Info for the alias field is a bit misleading IMO).

It is probably my fault that we have alias in P4Info today :), but maybe it's not too late to remove it. And if it is useful to someone, we should clearly define what it's for in the P4Runtime spec.

**Comment by teverman** [comment]
I would not object to removing the alias, assuming it's not of any use to the P4Runtime client.

**Comment by ccascone** [comment]
Same here, no objection about removing `alias` We don't use it in ONOS; northbound APIs expect entities such as tables, match fields, etc. to be referenced by their fully qualified `name`.

**Comment by antoninbas** [comment]
I didn't hear from @wmohsin on this, so I decided to keep alias, and just rephrase the comment a little bit (https://github.com/p4lang/p4runtime/pull/100). There is no harm in having this field after all. Since the p4 compiler has been generating this field for a while, we would have had to reserve the Protobuf id, and it seems like too much hassle to me. A controller / application can just choose to ignore this alias altogether.
